/**
 * POR Database Schema
 * 
 * This file was auto-generated by the query-por-schema-adodb.ts script
 * Last updated: 2025-03-27T00:33:11.050Z
 */

export interface PORTableColumn {
  name: string;
  dataType: string;
  size?: number;
  isNullable?: boolean;
}

export interface PORTableSchema {
  name: string;
  columns: PORTableColumn[];
}

export interface PORDatabaseSchema {
  tables: PORTableSchema[];
  databaseName: string;
  lastUpdated: string;
}

/**
 * Complete schema for the POR database
 */
export const porSchema: PORDatabaseSchema = {
  "tables": [
    {
      "name": "PurchaseOrder",
      "columns": [
        {
          "name": "ID",
          "dataType": "INTEGER"
        },
        {
          "name": "Date",
          "dataType": "DATE"
        },
        {
          "name": "VendorNumber",
          "dataType": "VARCHAR"
        },
        {
          "name": "Status",
          "dataType": "VARCHAR"
        },
        {
          "name": "Store",
          "dataType": "VARCHAR"
        },
        {
          "name": "Amount",
          "dataType": "CURRENCY"
        },
        {
          "name": "CreatedDate",
          "dataType": "DATE"
        },
        {
          "name": "UpdatedDate",
          "dataType": "DATE"
        }
      ]
    },
    {
      "name": "Rentals",
      "columns": [
        {
          "name": "ID",
          "dataType": "INTEGER"
        },
        {
          "name": "Status",
          "dataType": "VARCHAR"
        },
        {
          "name": "CreatedDate",
          "dataType": "DATE"
        },
        {
          "name": "CustomerID",
          "dataType": "VARCHAR"
        },
        {
          "name": "Amount",
          "dataType": "CURRENCY"
        }
      ]
    },
    {
      "name": "Customers",
      "columns": [
        {
          "name": "ID",
          "dataType": "INTEGER"
        },
        {
          "name": "Name",
          "dataType": "VARCHAR"
        },
        {
          "name": "Address",
          "dataType": "VARCHAR"
        },
        {
          "name": "City",
          "dataType": "VARCHAR"
        },
        {
          "name": "State",
          "dataType": "VARCHAR"
        },
        {
          "name": "ZipCode",
          "dataType": "VARCHAR"
        },
        {
          "name": "Phone",
          "dataType": "VARCHAR"
        },
        {
          "name": "Email",
          "dataType": "VARCHAR"
        }
      ]
    },
    {
      "name": "Inventory",
      "columns": [
        {
          "name": "ID",
          "dataType": "INTEGER"
        },
        {
          "name": "ItemNumber",
          "dataType": "VARCHAR"
        },
        {
          "name": "Description",
          "dataType": "VARCHAR"
        },
        {
          "name": "Quantity",
          "dataType": "INTEGER"
        },
        {
          "name": "Cost",
          "dataType": "CURRENCY"
        },
        {
          "name": "Price",
          "dataType": "CURRENCY"
        }
      ]
    },
    {
      "name": "Orders",
      "columns": [
        {
          "name": "ID",
          "dataType": "INTEGER"
        },
        {
          "name": "OrderType",
          "dataType": "VARCHAR"
        },
        {
          "name": "RentalStatus",
          "dataType": "VARCHAR"
        },
        {
          "name": "SO_DATE",
          "dataType": "DATE"
        },
        {
          "name": "CustomerID",
          "dataType": "VARCHAR"
        },
        {
          "name": "Amount",
          "dataType": "CURRENCY"
        },
        {
          "name": "Source",
          "dataType": "VARCHAR"
        }
      ]
    },
    {
      "name": "AccountingTransaction",
      "columns": [
        {
          "name": "ID",
          "dataType": "INTEGER"
        },
        {
          "name": "TransactionDate",
          "dataType": "DATE"
        },
        {
          "name": "Amount",
          "dataType": "CURRENCY"
        },
        {
          "name": "Type",
          "dataType": "VARCHAR"
        },
        {
          "name": "Description",
          "dataType": "VARCHAR"
        }
      ]
    }
  ],
  "databaseName": "POR",
  "lastUpdated": "2025-03-27T00:33:11.049Z"
};

/**
 * Get all table names from the POR database
 */
export function getPORTableNames(): string[] {
  return porSchema.tables.map(table => table.name);
}

/**
 * Get all columns for a specific table
 */
export function getPORTableColumns(tableName: string): PORTableColumn[] {
  const table = porSchema.tables.find(t => t.name.toLowerCase() === tableName.toLowerCase());
  return table ? table.columns : [];
}

/**
 * Get column names for a specific table
 */
export function getPORTableColumnNames(tableName: string): string[] {
  return getPORTableColumns(tableName).map(col => col.name);
}

/**
 * Check if a table exists in the POR database
 */
export function isPORTableExists(tableName: string): boolean {
  return porSchema.tables.some(t => t.name.toLowerCase() === tableName.toLowerCase());
}

/**
 * Check if a column exists in a specific table
 */
export function isPORColumnExists(tableName: string, columnName: string): boolean {
  const columns = getPORTableColumns(tableName);
  return columns.some(col => col.name.toLowerCase() === columnName.toLowerCase());
}
