/**
 * SINGLE SOURCE OF TRUTH for dashboard data
 * 
 * This file contains all SQL expressions, chart configurations, and server settings
 * for the Tallman Dashboard. This is the authoritative source that the database
 * will be initialized from.
 * 
 * When changes are made to the database through the admin interface, the "Save DB"
 * button will update this file directly.
 * 
 * When the "Load DB" button is clicked, the database will be populated from this file.
 * 
 * Last updated: 2025-03-28T00:09:35.765Z
 */

import type { SpreadsheetRow, ChartGroupSetting, ServerConfig } from './types';

// Chart data for the dashboard
export const dashboardData: SpreadsheetRow[] = [
  {
    "id": "1",
    "DataPoint": "AR Aging Amount Due 1-30 Days",
    "chartGroup": "AR Aging",
    "chartName": "",
    "variableName": "Amount Due",
    "serverName": "P21",
    "tableName": "dbo.ar_open_items",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(balance) as value FROM dbo.ar_open_items WITH (NOLOCK) WHERE DATEDIFF(day, due_date, GETDATE()) BETWEEN 1 AND 30",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:31.164Z"
  },
  {
    "id": "10",
    "DataPoint": "Accounts Payable May",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "1500",
    "lastUpdated": "2025-03-28T00:05:33.482Z"
  },
  {
    "id": "100",
    "DataPoint": "Historical Data Total, Apr",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:13.705Z"
  },
  {
    "id": "101",
    "DataPoint": "Historical Data Total, May",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:16.205Z"
  },
  {
    "id": "102",
    "DataPoint": "Historical Data Total, Jun",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:18.765Z"
  },
  {
    "id": "103",
    "DataPoint": "Historical Data Total, Jul",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:21.286Z"
  },
  {
    "id": "104",
    "DataPoint": "Historical Data Total, Aug",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:24.020Z"
  },
  {
    "id": "105",
    "DataPoint": "Historical Data Total, Sep",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:26.768Z"
  },
  {
    "id": "106",
    "DataPoint": "Historical Data Total, Oct",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:29.508Z"
  },
  {
    "id": "107",
    "DataPoint": "Historical Data Total, Nov",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:32.251Z"
  },
  {
    "id": "108",
    "DataPoint": "Historical Data Total, Dec",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:35.053Z"
  },
  {
    "id": "109",
    "DataPoint": "Inventory In Stock Dept, 100",
    "chartGroup": "Inventory",
    "chartName": "",
    "variableName": "In Stock",
    "serverName": "P21",
    "tableName": "dbo.inv_mast",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(qty_on_hand) as value FROM dbo.inv_mast WITH (NOLOCK) WHERE dept_code = '100'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:47:37.791Z"
  },
  {
    "id": "11",
    "DataPoint": "Accounts Payable Jun",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "1600",
    "lastUpdated": "2025-03-28T00:05:33.482Z"
  },
  {
    "id": "110",
    "DataPoint": "Inventory In Stock Dept, 101",
    "chartGroup": "Inventory",
    "chartName": "",
    "variableName": "In Stock",
    "serverName": "P21",
    "tableName": "dbo.inv_mast",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(qty_on_hand) as value FROM dbo.inv_mast WITH (NOLOCK) WHERE dept_code = '101'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:47:40.561Z"
  },
  {
    "id": "111",
    "DataPoint": "Inventory In Stock Dept, 102",
    "chartGroup": "Inventory",
    "chartName": "",
    "variableName": "In Stock",
    "serverName": "P21",
    "tableName": "dbo.inv_mast",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(qty_on_hand) as value FROM dbo.inv_mast WITH (NOLOCK) WHERE dept_code = '102'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:47:43.367Z"
  },
  {
    "id": "112",
    "DataPoint": "Inventory In Stock Dept, 207",
    "chartGroup": "Inventory",
    "chartName": "",
    "variableName": "In Stock",
    "serverName": "P21",
    "tableName": "dbo.inv_mast",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(qty_on_hand) as value FROM dbo.inv_mast WITH (NOLOCK) WHERE dept_code = '207'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:47:46.286Z"
  },
  {
    "id": "113",
    "DataPoint": "Inventory On Order Dept, 100",
    "chartGroup": "Inventory",
    "chartName": "",
    "variableName": "On Order",
    "serverName": "P21",
    "tableName": "dbo.inv_mast",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(qty_on_order) as value FROM dbo.inv_mast WITH (NOLOCK) WHERE dept_code = '100'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:47:49.166Z"
  },
  {
    "id": "114",
    "DataPoint": "Inventory On Order Dept, 101",
    "chartGroup": "Inventory",
    "chartName": "",
    "variableName": "On Order",
    "serverName": "P21",
    "tableName": "dbo.inv_mast",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(qty_on_order) as value FROM dbo.inv_mast WITH (NOLOCK) WHERE dept_code = '101'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:47:51.955Z"
  },
  {
    "id": "115",
    "DataPoint": "Inventory On Order Dept, 102",
    "chartGroup": "Inventory",
    "chartName": "",
    "variableName": "On Order",
    "serverName": "P21",
    "tableName": "dbo.inv_mast",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(qty_on_order) as value FROM dbo.inv_mast WITH (NOLOCK) WHERE dept_code = '102'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:47:54.891Z"
  },
  {
    "id": "116",
    "DataPoint": "Inventory On Order Dept, 207",
    "chartGroup": "Inventory",
    "chartName": "",
    "variableName": "On Order",
    "serverName": "P21",
    "tableName": "dbo.inv_mast",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(qty_on_order) as value FROM dbo.inv_mast WITH (NOLOCK) WHERE dept_code = '207'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:47:57.717Z"
  },
  {
    "id": "117",
    "DataPoint": "Key Metrics Total Orders Overview",
    "chartGroup": "Key Metrics",
    "chartName": "",
    "variableName": "Total Orders",
    "serverName": "P21",
    "tableName": "TBD",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) AS value FROM dbo.oe_hdr WITH (NOLOCK) WHERE order_date >= DATEADD(day, -DATEPART(day, GETDATE()) + 1, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) AND order_date < DATEADD(month, 1, DATEADD(day, -DATEPART(day, GETDATE()) + 1, CAST(CAST(GETDATE() AS DATE) AS DATETIME)))",
    "value": "31",
    "lastUpdated": "2025-03-27T23:48:00.690Z"
  },
  {
    "id": "118",
    "DataPoint": "Key Metrics Open Orders (/day) Overview",
    "chartGroup": "Key Metrics",
    "chartName": "",
    "variableName": "Open Orders (/day)",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE order_status = 'Open'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:03.432Z"
  },
  {
    "id": "119",
    "DataPoint": "Key Metrics All Open Orders Overview",
    "chartGroup": "Key Metrics",
    "chartName": "",
    "variableName": "All Open Orders",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE order_status = 'Open'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:06.176Z"
  },
  {
    "id": "12",
    "DataPoint": "Accounts Payable Jul",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "1700",
    "lastUpdated": "2025-03-28T00:05:33.483Z"
  },
  {
    "id": "120",
    "DataPoint": "Key Metrics Daily Revenue Overview",
    "chartGroup": "Key Metrics",
    "chartName": "",
    "variableName": "Daily Revenue",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(total_amt) as value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE MONTH(invoice_date) = MONTH(GETDATE()) AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:08.911Z"
  },
  {
    "id": "121",
    "DataPoint": "Key Metrics Open Invoices Overview",
    "chartGroup": "Key Metrics",
    "chartName": "",
    "variableName": "Open Invoices",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE status = 'Open'",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:11.694Z"
  },
  {
    "id": "122",
    "DataPoint": "Key Metrics OrdersBackloged Overview",
    "chartGroup": "Key Metrics",
    "chartName": "",
    "variableName": "OrdersBackloged",
    "serverName": "P21",
    "tableName": "TBD",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) AS value FROM dbo.oe_hdr WITH (NOLOCK) WHERE completed = 'N' AND order_date >= DATEADD(day, -30, GETDATE())",
    "value": "30",
    "lastUpdated": "2025-03-27T23:48:14.246Z"
  },
  {
    "id": "123",
    "DataPoint": "Key Metrics Total Sales Monthly Overview",
    "chartGroup": "Key Metrics",
    "chartName": "",
    "variableName": "Total Sales Monthly",
    "serverName": "P21",
    "tableName": "TBD",
    "calculation": "number",
    "productionSqlExpression": "SELECT CAST(ISNULL(SUM(l.extended_price), 0) AS DECIMAL(18,2)) AS value FROM dbo.oe_hdr h WITH (NOLOCK) JOIN dbo.oe_line l WITH (NOLOCK) ON h.order_no = l.order_no WHERE h.order_date >= DATEADD(day, -DATEPART(day, GETDATE()) + 1, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) AND h.order_date < DATEADD(month, 1, DATEADD(day, -DATEPART(day, GETDATE()) + 1, CAST(CAST(GETDATE() AS DATE) AS DATETIME)))",
    "value": "$2,185,470",
    "lastUpdated": "2025-03-27T23:48:16.848Z"
  },
  {
    "id": "124",
    "DataPoint": "Site Distribution Value Columbus",
    "chartGroup": "Site Distribution",
    "chartName": "",
    "variableName": "Value",
    "serverName": "P21",
    "tableName": "TBD",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.site_distribution WITH (NOLOCK) WHERE MONTH(create_date) = 1",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:19.350Z"
  },
  {
    "id": "125",
    "DataPoint": "Site Distribution Value Addison",
    "chartGroup": "Site Distribution",
    "chartName": "",
    "variableName": "Value",
    "serverName": "P21",
    "tableName": "TBD",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.site_distribution WITH (NOLOCK) WHERE MONTH(create_date) = 1",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:22.070Z"
  },
  {
    "id": "126",
    "DataPoint": "Site Distribution Value Lake City",
    "chartGroup": "Site Distribution",
    "chartName": "",
    "variableName": "Value",
    "serverName": "P21",
    "tableName": "TBD",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.site_distribution WITH (NOLOCK) WHERE MONTH(create_date) = 1",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:19.353Z"
  },
  {
    "id": "127",
    "DataPoint": "POR Overview New Rentals, Jan",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 1 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:22.057Z"
  },
  {
    "id": "128",
    "DataPoint": "POR Overview New Rentals, Feb",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 2 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:26.485Z"
  },
  {
    "id": "129",
    "DataPoint": "POR Overview New Rentals, Mar",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 3 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:29.237Z"
  },
  {
    "id": "13",
    "DataPoint": "Accounts Payable Aug",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "1800",
    "lastUpdated": "2025-03-28T00:05:33.483Z"
  },
  {
    "id": "130",
    "DataPoint": "POR Overview New Rentals, Apr",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 4 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:31.713Z"
  },
  {
    "id": "131",
    "DataPoint": "POR Overview New Rentals, May",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 5 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:34.458Z"
  },
  {
    "id": "132",
    "DataPoint": "POR Overview New Rentals, Jun",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 6 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:37.502Z"
  },
  {
    "id": "133",
    "DataPoint": "POR Overview New Rentals, Jul",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 7 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:40.000Z"
  },
  {
    "id": "134",
    "DataPoint": "POR Overview New Rentals, Aug",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 8 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:42.754Z"
  },
  {
    "id": "135",
    "DataPoint": "POR Overview New Rentals, Sep",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 9 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:45.653Z"
  },
  {
    "id": "136",
    "DataPoint": "POR Overview New Rentals, Oct",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 10 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:48.487Z"
  },
  {
    "id": "137",
    "DataPoint": "POR Overview New Rentals, Nov",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 11 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:51.380Z"
  },
  {
    "id": "138",
    "DataPoint": "POR Overview New Rentals, Dec",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "New Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'New' AND DatePart('m', RentalDate) = 12 AND DatePart('yyyy', RentalDate) = DatePart('yyyy', Now())",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:54.165Z"
  },
  {
    "id": "139",
    "DataPoint": "POR Overview Open Rentals, Jan",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 1",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:57.104Z"
  },
  {
    "id": "14",
    "DataPoint": "Accounts Payable Sep",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "1900",
    "lastUpdated": "2025-03-28T00:05:33.484Z"
  },
  {
    "id": "140",
    "DataPoint": "POR Overview Open Rentals, Feb",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 2",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:00.011Z"
  },
  {
    "id": "141",
    "DataPoint": "POR Overview Open Rentals, Mar",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 3",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:02.887Z"
  },
  {
    "id": "142",
    "DataPoint": "POR Overview Open Rentals, Apr",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 4",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:05.629Z"
  },
  {
    "id": "143",
    "DataPoint": "POR Overview Open Rentals, May",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 5",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:08.383Z"
  },
  {
    "id": "144",
    "DataPoint": "POR Overview Open Rentals, Jun",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 6",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:11.125Z"
  },
  {
    "id": "145",
    "DataPoint": "POR Overview Open Rentals, Jul",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 7",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:13.927Z"
  },
  {
    "id": "146",
    "DataPoint": "POR Overview Open Rentals, Aug",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 8",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:16.524Z"
  },
  {
    "id": "147",
    "DataPoint": "POR Overview Open Rentals, Sep",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 9",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:19.064Z"
  },
  {
    "id": "148",
    "DataPoint": "POR Overview Open Rentals, Oct",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 10",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:21.551Z"
  },
  {
    "id": "149",
    "DataPoint": "POR Overview Open Rentals, Nov",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 11",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:45.939Z"
  },
  {
    "id": "15",
    "DataPoint": "Accounts Payable Oct",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "2000",
    "lastUpdated": "2025-03-28T00:05:33.484Z"
  },
  {
    "id": "150",
    "DataPoint": "POR Overview Open Rentals, Dec",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Rentals WHERE Status = 'Open' AND DatePart('m', RentalDate) = 12",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:49.121Z"
  },
  {
    "id": "151",
    "DataPoint": "POR Overview Rental Value, Jan",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 1",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:51.668Z"
  },
  {
    "id": "152",
    "DataPoint": "POR Overview Rental Value, Feb",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 2",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:54.847Z"
  },
  {
    "id": "153",
    "DataPoint": "POR Overview Rental Value, Mar",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 3",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:47:57.677Z"
  },
  {
    "id": "154",
    "DataPoint": "POR Overview Rental Value, Apr",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 4",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:00.299Z"
  },
  {
    "id": "155",
    "DataPoint": "POR Overview Rental Value, May",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 5",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:03.387Z"
  },
  {
    "id": "156",
    "DataPoint": "POR Overview Rental Value, Jun",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 6",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:05.880Z"
  },
  {
    "id": "157",
    "DataPoint": "POR Overview Rental Value, Jul",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 7",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:08.876Z"
  },
  {
    "id": "158",
    "DataPoint": "POR Overview Rental Value, Aug",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 8",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:11.404Z"
  },
  {
    "id": "159",
    "DataPoint": "POR Overview Rental Value, Sep",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 9",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:14.213Z"
  },
  {
    "id": "16",
    "DataPoint": "Accounts Payable Nov",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "2100",
    "lastUpdated": "2025-03-28T00:05:33.485Z"
  },
  {
    "id": "160",
    "DataPoint": "POR Overview Rental Value, Oct",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 10",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:16.785Z"
  },
  {
    "id": "161",
    "DataPoint": "POR Overview Rental Value, Nov",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 11",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:19.308Z"
  },
  {
    "id": "162",
    "DataPoint": "POR Overview Rental Value, Dec",
    "chartGroup": "POR Overview",
    "chartName": "",
    "variableName": "Rental Value",
    "serverName": "POR",
    "tableName": "Rentals",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(RentalValue) as value FROM Rentals WHERE DatePart('m', RentalDate) = 12",
    "value": "Table 'Rentals' not found in the database",
    "lastUpdated": "2025-03-27T23:48:21.797Z"
  },
  {
    "id": "163",
    "DataPoint": "Web Orders Orders, Jan",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 1",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:14.250Z"
  },
  {
    "id": "164",
    "DataPoint": "Web Orders Orders, Feb",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 2",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:16.842Z"
  },
  {
    "id": "165",
    "DataPoint": "Web Orders Orders, Mar",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 3",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:19.357Z"
  },
  {
    "id": "166",
    "DataPoint": "Web Orders Orders, Apr",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 4",
    "value": "1",
    "lastUpdated": "2025-03-27T23:48:22.078Z"
  },
  {
    "id": "167",
    "DataPoint": "Web Orders Orders, May",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 5",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:12.852Z"
  },
  {
    "id": "168",
    "DataPoint": "Web Orders Orders, Jun",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 6",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:14.875Z"
  },
  {
    "id": "169",
    "DataPoint": "Web Orders Orders, Jul",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 7",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:16.898Z"
  },
  {
    "id": "17",
    "DataPoint": "Accounts Payable Dec",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "2200",
    "lastUpdated": "2025-03-28T00:05:33.486Z"
  },
  {
    "id": "170",
    "DataPoint": "Web Orders Orders, Aug",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 8",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:18.922Z"
  },
  {
    "id": "171",
    "DataPoint": "Web Orders Orders, Sep",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 9",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:20.948Z"
  },
  {
    "id": "172",
    "DataPoint": "Web Orders Orders, Oct",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 10",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:23.027Z"
  },
  {
    "id": "173",
    "DataPoint": "Web Orders Orders, Nov",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 11",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:25.055Z"
  },
  {
    "id": "174",
    "DataPoint": "Web Orders Orders, Dec",
    "chartGroup": "Web Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "Orders",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Orders WHERE Source = 'Web' AND DatePart('m', OrderDate) = 12",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:27.133Z"
  },
  {
    "id": "18",
    "DataPoint": "Accounts Receivable Jan",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 1 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "2100",
    "lastUpdated": "2025-03-28T00:09:35.753Z"
  },
  {
    "id": "19",
    "DataPoint": "Accounts Receivable Feb",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 2 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "2200",
    "lastUpdated": "2025-03-28T00:09:35.755Z"
  },
  {
    "id": "2",
    "DataPoint": "AR Aging Amount Due 31-60 Days",
    "chartGroup": "AR Aging",
    "chartName": "",
    "variableName": "Amount Due",
    "serverName": "P21",
    "tableName": "dbo.ar_open_items",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(balance) as value FROM dbo.ar_open_items WITH (NOLOCK) WHERE DATEDIFF(day, due_date, GETDATE()) BETWEEN 31 AND 60",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:33.194Z"
  },
  {
    "id": "20",
    "DataPoint": "Accounts Receivable Mar",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 3 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "2300",
    "lastUpdated": "2025-03-28T00:09:35.755Z"
  },
  {
    "id": "21",
    "DataPoint": "Accounts Receivable Apr",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 4 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "2400",
    "lastUpdated": "2025-03-28T00:09:35.756Z"
  },
  {
    "id": "22",
    "DataPoint": "Accounts Receivable May",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 5 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "2500",
    "lastUpdated": "2025-03-28T00:09:35.756Z"
  },
  {
    "id": "23",
    "DataPoint": "Accounts Receivable Jun",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 6 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "2600",
    "lastUpdated": "2025-03-28T00:09:35.757Z"
  },
  {
    "id": "24",
    "DataPoint": "Accounts Receivable Jul",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 7 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "2700",
    "lastUpdated": "2025-03-28T00:09:35.757Z"
  },
  {
    "id": "25",
    "DataPoint": "Accounts Receivable Aug",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 8 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "2800",
    "lastUpdated": "2025-03-28T00:09:35.757Z"
  },
  {
    "id": "26",
    "DataPoint": "Accounts Receivable Sep",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 9 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "2900",
    "lastUpdated": "2025-03-28T00:09:35.758Z"
  },
  {
    "id": "27",
    "DataPoint": "Accounts Receivable Oct",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 10 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "3000",
    "lastUpdated": "2025-03-28T00:09:35.758Z"
  },
  {
    "id": "28",
    "DataPoint": "Accounts Receivable Nov",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 11 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "3100",
    "lastUpdated": "2025-03-28T00:09:35.759Z"
  },
  {
    "id": "29",
    "DataPoint": "Accounts Receivable Dec",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Receivable",
    "serverName": "P21",
    "tableName": "dbo.temp_invoice_summary",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(summary_group_code) as value FROM dbo.temp_invoice_summary WITH (NOLOCK) WHERE MONTH(invoice_date) = 12 AND YEAR(invoice_date) = YEAR(GETDATE())",
    "value": "3200",
    "lastUpdated": "2025-03-28T00:09:35.759Z"
  },
  {
    "id": "3",
    "DataPoint": "AR Aging Amount Due 61-90 Days",
    "chartGroup": "AR Aging",
    "chartName": "",
    "variableName": "Amount Due",
    "serverName": "P21",
    "tableName": "dbo.ar_open_items",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(balance) as value FROM dbo.ar_open_items WITH (NOLOCK) WHERE DATEDIFF(day, due_date, GETDATE()) BETWEEN 61 AND 90",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:35.220Z"
  },
  {
    "id": "30",
    "DataPoint": "Accounts Overdue Jan",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "550",
    "lastUpdated": "2025-03-28T00:05:33.491Z"
  },
  {
    "id": "31",
    "DataPoint": "Accounts Overdue Feb",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "600",
    "lastUpdated": "2025-03-28T00:05:33.492Z"
  },
  {
    "id": "32",
    "DataPoint": "Accounts Overdue Mar",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "650",
    "lastUpdated": "2025-03-28T00:05:33.492Z"
  },
  {
    "id": "33",
    "DataPoint": "Accounts Overdue Apr",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "700",
    "lastUpdated": "2025-03-28T00:05:33.493Z"
  },
  {
    "id": "34",
    "DataPoint": "Accounts Overdue May",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "750",
    "lastUpdated": "2025-03-28T00:05:33.493Z"
  },
  {
    "id": "35",
    "DataPoint": "Accounts Overdue Jun",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "800",
    "lastUpdated": "2025-03-28T00:05:33.493Z"
  },
  {
    "id": "36",
    "DataPoint": "Accounts Overdue Jul",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "850",
    "lastUpdated": "2025-03-28T00:05:33.494Z"
  },
  {
    "id": "37",
    "DataPoint": "Accounts Overdue Aug",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "900",
    "lastUpdated": "2025-03-28T00:05:33.494Z"
  },
  {
    "id": "38",
    "DataPoint": "Accounts Overdue Sep",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "950",
    "lastUpdated": "2025-03-28T00:05:33.494Z"
  },
  {
    "id": "39",
    "DataPoint": "Accounts Overdue Oct",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "1000",
    "lastUpdated": "2025-03-28T00:05:33.495Z"
  },
  {
    "id": "4",
    "DataPoint": "AR Aging Amount Due 90+ Days",
    "chartGroup": "AR Aging",
    "chartName": "",
    "variableName": "Amount Due",
    "serverName": "P21",
    "tableName": "dbo.ar_open_items",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(balance) as value FROM dbo.ar_open_items WITH (NOLOCK) WHERE DATEDIFF(day, due_date, GETDATE()) > 90",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:37.244Z"
  },
  {
    "id": "40",
    "DataPoint": "Accounts Overdue Nov",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "1050",
    "lastUpdated": "2025-03-28T00:05:33.495Z"
  },
  {
    "id": "41",
    "DataPoint": "Accounts Overdue Dec",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Overdue",
    "serverName": "P21",
    "tableName": "dbo.ar_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ar_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL AND DATEDIFF(day, due_date, GETDATE()) > 30",
    "value": "1100",
    "lastUpdated": "2025-03-28T00:05:33.495Z"
  },
  {
    "id": "42",
    "DataPoint": "Customer Metrics New, Jan",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 1 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:10.376Z"
  },
  {
    "id": "43",
    "DataPoint": "Customer Metrics New, Feb",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 2 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:12.432Z"
  },
  {
    "id": "44",
    "DataPoint": "Customer Metrics New, Mar",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 3 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:14.479Z"
  },
  {
    "id": "45",
    "DataPoint": "Customer Metrics New, Apr",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 4 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:16.528Z"
  },
  {
    "id": "46",
    "DataPoint": "Customer Metrics New, May",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 5 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:18.579Z"
  },
  {
    "id": "47",
    "DataPoint": "Customer Metrics New, Jun",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 6 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:20.633Z"
  },
  {
    "id": "48",
    "DataPoint": "Customer Metrics New, Jul",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 7 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:22.681Z"
  },
  {
    "id": "49",
    "DataPoint": "Customer Metrics New, Aug",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 8 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:24.733Z"
  },
  {
    "id": "5",
    "DataPoint": "AR Aging Amount Due Current",
    "chartGroup": "AR Aging",
    "chartName": "",
    "variableName": "Amount Due",
    "serverName": "P21",
    "tableName": "dbo.ar_open_items",
    "calculation": "number",
    "productionSqlExpression": "SELECT SUM(balance) as value FROM dbo.ar_open_items WITH (NOLOCK) WHERE due_date >= GETDATE()",
    "value": "1",
    "lastUpdated": "2025-03-27T23:43:39.268Z"
  },
  {
    "id": "50",
    "DataPoint": "Customer Metrics New, Sep",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 9 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:26.778Z"
  },
  {
    "id": "51",
    "DataPoint": "Customer Metrics New, Oct",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 10 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:28.816Z"
  },
  {
    "id": "52",
    "DataPoint": "Customer Metrics New, Nov",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 11 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:30.852Z"
  },
  {
    "id": "53",
    "DataPoint": "Customer Metrics New, Dec",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "New",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE MONTH(create_date) = 12 AND YEAR(create_date) = YEAR(GETDATE())",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:32.884Z"
  },
  {
    "id": "54",
    "DataPoint": "Customer Metrics Prospects, Jan",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 1",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:34.911Z"
  },
  {
    "id": "55",
    "DataPoint": "Customer Metrics Prospects, Feb",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 2",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:36.938Z"
  },
  {
    "id": "56",
    "DataPoint": "Customer Metrics Prospects, Mar",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 3",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:38.967Z"
  },
  {
    "id": "57",
    "DataPoint": "Customer Metrics Prospects, Apr",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 4",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:40.995Z"
  },
  {
    "id": "58",
    "DataPoint": "Customer Metrics Prospects, May",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 5",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:43.024Z"
  },
  {
    "id": "59",
    "DataPoint": "Customer Metrics Prospects, Jun",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 6",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:45.057Z"
  },
  {
    "id": "6",
    "DataPoint": "Accounts Payable Jan",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "1100",
    "lastUpdated": "2025-03-28T00:05:33.478Z"
  },
  {
    "id": "60",
    "DataPoint": "Customer Metrics Prospects, Jul",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 7",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:47.096Z"
  },
  {
    "id": "61",
    "DataPoint": "Customer Metrics Prospects, Aug",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 8",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:49.122Z"
  },
  {
    "id": "62",
    "DataPoint": "Customer Metrics Prospects, Sep",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 9",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:20.629Z"
  },
  {
    "id": "63",
    "DataPoint": "Customer Metrics Prospects, Oct",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 10",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:22.677Z"
  },
  {
    "id": "64",
    "DataPoint": "Customer Metrics Prospects, Nov",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 11",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:24.727Z"
  },
  {
    "id": "65",
    "DataPoint": "Customer Metrics Prospects, Dec",
    "chartGroup": "Customer Metrics",
    "chartName": "",
    "variableName": "Prospects",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.customer WITH (NOLOCK) WHERE cust_type = 'Prospect' AND MONTH(create_date) = 12",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:26.774Z"
  },
  {
    "id": "66",
    "DataPoint": "Daily Orders Orders Today",
    "chartGroup": "Daily Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE DATEDIFF(day, order_date, GETDATE()) = 0",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:28.830Z"
  },
  {
    "id": "67",
    "DataPoint": "Daily Orders Orders Today-, 1",
    "chartGroup": "Daily Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE DATEDIFF(day, order_date, GETDATE()) = 1",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:30.875Z"
  },
  {
    "id": "68",
    "DataPoint": "Daily Orders Orders Today-, 2",
    "chartGroup": "Daily Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE DATEDIFF(day, order_date, GETDATE()) = 2",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:32.924Z"
  },
  {
    "id": "69",
    "DataPoint": "Daily Orders Orders Today-, 3",
    "chartGroup": "Daily Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE DATEDIFF(day, order_date, GETDATE()) = 3",
    "value": "3",
    "lastUpdated": "2025-03-27T23:44:35.000Z"
  },
  {
    "id": "7",
    "DataPoint": "Accounts Payable Feb",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "1200",
    "lastUpdated": "2025-03-28T00:05:33.481Z"
  },
  {
    "id": "70",
    "DataPoint": "Daily Orders Orders Today-, 4",
    "chartGroup": "Daily Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE DATEDIFF(day, order_date, GETDATE()) = 4",
    "value": "1",
    "lastUpdated": "2025-03-27T23:44:37.050Z"
  },
  {
    "id": "71",
    "DataPoint": "Daily Orders Orders Today-, 5",
    "chartGroup": "Daily Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE DATEDIFF(day, order_date, GETDATE()) = 5",
    "value": "4",
    "lastUpdated": "2025-03-27T23:44:39.109Z"
  },
  {
    "id": "72",
    "DataPoint": "Daily Orders Orders Today-, 6",
    "chartGroup": "Daily Orders",
    "chartName": "",
    "variableName": "Orders",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE DATEDIFF(day, order_date, GETDATE()) = 6",
    "value": "4",
    "lastUpdated": "2025-03-27T23:44:41.166Z"
  },
  {
    "id": "73",
    "DataPoint": "Historical Data P21, Jan",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1",
    "value": "46716",
    "lastUpdated": "2025-03-27T23:44:43.229Z"
  },
  {
    "id": "74",
    "DataPoint": "Historical Data P21, Feb",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 2",
    "value": "45129",
    "lastUpdated": "2025-03-27T23:44:45.294Z"
  },
  {
    "id": "75",
    "DataPoint": "Historical Data P21, Mar",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 3",
    "value": "50145",
    "lastUpdated": "2025-03-27T23:44:47.355Z"
  },
  {
    "id": "76",
    "DataPoint": "Historical Data P21, Apr",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 4",
    "value": "42843",
    "lastUpdated": "2025-03-27T23:44:49.506Z"
  },
  {
    "id": "77",
    "DataPoint": "Historical Data P21, May",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 5",
    "value": "40991",
    "lastUpdated": "2025-03-27T23:44:43.262Z"
  },
  {
    "id": "78",
    "DataPoint": "Historical Data P21, Jun",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 6",
    "value": "39760",
    "lastUpdated": "2025-03-27T23:44:45.326Z"
  },
  {
    "id": "79",
    "DataPoint": "Historical Data P21, Jul",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 7",
    "value": "38108",
    "lastUpdated": "2025-03-27T23:44:47.382Z"
  },
  {
    "id": "8",
    "DataPoint": "Accounts Payable Mar",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "1300",
    "lastUpdated": "2025-03-28T00:05:33.481Z"
  },
  {
    "id": "80",
    "DataPoint": "Historical Data P21, Aug",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 8",
    "value": "44797",
    "lastUpdated": "2025-03-27T23:44:49.515Z"
  },
  {
    "id": "81",
    "DataPoint": "Historical Data P21, Sep",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 9",
    "value": "43207",
    "lastUpdated": "2025-03-27T23:39:28.020Z"
  },
  {
    "id": "82",
    "DataPoint": "Historical Data P21, Oct",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 10",
    "value": "47633",
    "lastUpdated": "2025-03-27T23:39:30.123Z"
  },
  {
    "id": "83",
    "DataPoint": "Historical Data P21, Nov",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 11",
    "value": "38225",
    "lastUpdated": "2025-03-27T23:39:32.465Z"
  },
  {
    "id": "84",
    "DataPoint": "Historical Data P21, Dec",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "P21",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 12",
    "value": "33134",
    "lastUpdated": "2025-03-27T23:46:29.430Z"
  },
  {
    "id": "85",
    "DataPoint": "Historical Data POR, Jan",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:31.908Z"
  },
  {
    "id": "86",
    "DataPoint": "Historical Data POR, Feb",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 2 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:34.374Z"
  },
  {
    "id": "87",
    "DataPoint": "Historical Data POR, Mar",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 3 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:37.398Z"
  },
  {
    "id": "88",
    "DataPoint": "Historical Data POR, Apr",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 4 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:40.183Z"
  },
  {
    "id": "89",
    "DataPoint": "Historical Data POR, May",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 5 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:42.941Z"
  },
  {
    "id": "9",
    "DataPoint": "Accounts Payable Apr",
    "chartGroup": "Accounts",
    "chartName": "",
    "variableName": "Payable",
    "serverName": "P21",
    "tableName": "dbo.ap_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT COUNT(*) as value FROM dbo.ap_hdr WITH (NOLOCK) WHERE invoice_date IS NOT NULL",
    "value": "1400",
    "lastUpdated": "2025-03-28T00:05:33.482Z"
  },
  {
    "id": "90",
    "DataPoint": "Historical Data POR, Jun",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 6 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:45.455Z"
  },
  {
    "id": "91",
    "DataPoint": "Historical Data POR, Jul",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 7 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:48.199Z"
  },
  {
    "id": "92",
    "DataPoint": "Historical Data POR, Aug",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 8 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:51.167Z"
  },
  {
    "id": "93",
    "DataPoint": "Historical Data POR, Sep",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 9 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:54.487Z"
  },
  {
    "id": "94",
    "DataPoint": "Historical Data POR, Oct",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 10 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:46:58.155Z"
  },
  {
    "id": "95",
    "DataPoint": "Historical Data POR, Nov",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 11 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:00.892Z"
  },
  {
    "id": "96",
    "DataPoint": "Historical Data POR, Dec",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "POR",
    "serverName": "POR",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) AS value FROM PurchaseOrderDetail WHERE Month(Date) = 12 AND Year(Date) = Year(Date())",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:03.651Z"
  },
  {
    "id": "97",
    "DataPoint": "Historical Data Total, Jan",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:06.216Z"
  },
  {
    "id": "98",
    "DataPoint": "Historical Data Total, Feb",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:08.704Z"
  },
  {
    "id": "99",
    "DataPoint": "Historical Data Total, Mar",
    "chartGroup": "Historical Data",
    "chartName": "",
    "variableName": "Total",
    "serverName": "P21",
    "tableName": "dbo.oe_hdr",
    "calculation": "number",
    "productionSqlExpression": "SELECT (SELECT COUNT(*) FROM dbo.oe_hdr WITH (NOLOCK) WHERE MONTH(order_date) = 1 AND YEAR(order_date) = YEAR(GETDATE())) + (SELECT Count(*) FROM PurchaseOrderDetail WHERE Month(Date) = 1 AND Year(Date) = Year(Date())) AS value",
    "value": "2",
    "lastUpdated": "2025-03-27T23:47:11.202Z"
  }
];

// Chart group settings
export const chartGroupSettings: ChartGroupSetting[] = [
  {
    "id": "1",
    "name": "AR Aging",
    "display_order": 1,
    "is_visible": 1,
    "settings": {
      "chartType": "bar"
    }
  },
  {
    "id": "2",
    "name": "Accounts",
    "display_order": 2,
    "is_visible": 1,
    "settings": {
      "chartType": "line"
    }
  },
  {
    "id": "3",
    "name": "Customer Metrics",
    "display_order": 3,
    "is_visible": 1,
    "settings": {
      "chartType": "line"
    }
  },
  {
    "id": "4",
    "name": "Daily Orders",
    "display_order": 4,
    "is_visible": 1,
    "settings": {
      "chartType": "bar"
    }
  },
  {
    "id": "5",
    "name": "Historical Data",
    "display_order": 5,
    "is_visible": 1,
    "settings": {
      "chartType": "line"
    }
  },
  {
    "id": "6",
    "name": "Inventory",
    "display_order": 6,
    "is_visible": 1,
    "settings": {
      "chartType": "bar"
    }
  },
  {
    "id": "7",
    "name": "Key Metrics",
    "display_order": 7,
    "is_visible": 1,
    "settings": {
      "chartType": "value"
    }
  },
  {
    "id": "8",
    "name": "Site Distribution",
    "display_order": 8,
    "is_visible": 1,
    "settings": {
      "chartType": "pie"
    }
  },
  {
    "id": "9",
    "name": "POR Overview",
    "display_order": 9,
    "is_visible": 1,
    "settings": {
      "chartType": "line"
    }
  },
  {
    "id": "10",
    "name": "Web Orders",
    "display_order": 10,
    "is_visible": 1,
    "settings": {
      "chartType": "line"
    }
  }
];

// Server configurations
export const serverConfigs: ServerConfig[] = [
  {
    "id": "1",
    "name": "P21",
    "host": "localhost",
    "port": 1433,
    "database": "P21",
    "username": "sa",
    "password": "password",
    "is_active": 1,
    "connection_type": "sqlserver",
    "server": "localhost",
    "created_at": "2025-03-27T23:25:35.905Z",
    "updated_at": "2025-03-27T23:25:35.906Z",
    "config": {}
  },
  {
    "id": "2",
    "name": "POR",
    "host": "localhost",
    "port": 0,
    "database": "C:\\POR\\PORData.mdb",
    "username": "admin",
    "password": "",
    "is_active": 1,
    "connection_type": "access",
    "server": "localhost",
    "created_at": "2025-03-27T23:25:35.906Z",
    "updated_at": "2025-03-27T23:25:35.906Z",
    "config": {}
  }
];