import type { ChartDataRow } from './types';

// This type represents the static definition needed for each row.
// 'id' (db primary key), 'value', 'lastUpdated' are excluded as they are dynamic.
// Use Omit to define the specific structure we are exporting
export type SourceDataDefinition = Omit<ChartDataRow, 'id' | 'value' | 'lastUpdated'>;

export const singleSourceData: SourceDataDefinition[] = [
  {
    "rowId": "1",
    "chartGroup": "AR Aging",
    "variableName": "Amount Due",
    "DataPoint": "AR Aging Amount Due 1-30 Days",
    "serverName": "P21",
    "tableName": "ar_aging",
    "productionSqlExpression": "SELECT SUM(amount_due) AS result FROM ar_aging WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "AR Aging Chart",
    "axisStep": null
  },
  {
    "rowId": "2",
    "chartGroup": "AR Aging",
    "variableName": "Amount Due",
    "DataPoint": "AR Aging Amount Due 31-60 Days",
    "serverName": "P21",
    "tableName": "ar_aging",
    "productionSqlExpression": "SELECT SUM(amount_due) AS result FROM ar_aging WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "AR Aging Chart",
    "axisStep": null
  },
  {
    "rowId": "3",
    "chartGroup": "AR Aging",
    "variableName": "Amount Due",
    "DataPoint": "AR Aging Amount Due 61-90 Days",
    "serverName": "P21",
    "tableName": "ar_aging",
    "productionSqlExpression": "SELECT SUM(amount_due) AS result FROM ar_aging WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "AR Aging Chart",
    "axisStep": null
  },
  {
    "rowId": "4",
    "chartGroup": "AR Aging",
    "variableName": "Amount Due",
    "DataPoint": "AR Aging Amount Due 90+ Days",
    "serverName": "P21",
    "tableName": "ar_aging",
    "productionSqlExpression": "SELECT SUM(amount_due) AS result FROM ar_aging WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "AR Aging Chart",
    "axisStep": null
  },
  {
    "rowId": "5",
    "chartGroup": "AR Aging",
    "variableName": "Amount Due",
    "DataPoint": "AR Aging Amount Due Current",
    "serverName": "P21",
    "tableName": "ar_aging",
    "productionSqlExpression": "SELECT SUM(amount_due) AS result FROM ar_aging WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "AR Aging Chart",
    "axisStep": null
  },
  {
    "rowId": "6",
    "chartGroup": "Accounts",
    "variableName": "Payable, Jan",
    "DataPoint": "Accounts Payable Jan",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "7",
    "chartGroup": "Accounts",
    "variableName": "Payable, Feb",
    "DataPoint": "Accounts Payable Feb",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "8",
    "chartGroup": "Accounts",
    "variableName": "Payable, Mar",
    "DataPoint": "Accounts Payable Mar",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "9",
    "chartGroup": "Accounts",
    "variableName": "Payable, Apr",
    "DataPoint": "Accounts Payable Apr",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "10",
    "chartGroup": "Accounts",
    "variableName": "Payable, May",
    "DataPoint": "Accounts Payable May",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "11",
    "chartGroup": "Accounts",
    "variableName": "Payable, Jun",
    "DataPoint": "Accounts Payable Jun",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "12",
    "chartGroup": "Accounts",
    "variableName": "Payable, Jul",
    "DataPoint": "Accounts Payable Jul",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "13",
    "chartGroup": "Accounts",
    "variableName": "Payable, Aug",
    "DataPoint": "Accounts Payable Aug",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "14",
    "chartGroup": "Accounts",
    "variableName": "Payable, Sep",
    "DataPoint": "Accounts Payable Sep",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "15",
    "chartGroup": "Accounts",
    "variableName": "Payable, Oct",
    "DataPoint": "Accounts Payable Oct",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "16",
    "chartGroup": "Accounts",
    "variableName": "Payable, Nov",
    "DataPoint": "Accounts Payable Nov",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "17",
    "chartGroup": "Accounts",
    "variableName": "Payable, Dec",
    "DataPoint": "Accounts Payable Dec",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(payable) AS result FROM rental_accounts WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "18",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Jan",
    "DataPoint": "Accounts Receivable Jan",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "19",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Feb",
    "DataPoint": "Accounts Receivable Feb",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "20",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Mar",
    "DataPoint": "Accounts Receivable Mar",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "21",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Apr",
    "DataPoint": "Accounts Receivable Apr",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "22",
    "chartGroup": "Accounts",
    "variableName": "Receivable, May",
    "DataPoint": "Accounts Receivable May",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "23",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Jun",
    "DataPoint": "Accounts Receivable Jun",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "24",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Jul",
    "DataPoint": "Accounts Receivable Jul",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "25",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Aug",
    "DataPoint": "Accounts Receivable Aug",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "26",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Sep",
    "DataPoint": "Accounts Receivable Sep",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "27",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Oct",
    "DataPoint": "Accounts Receivable Oct",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "28",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Nov",
    "DataPoint": "Accounts Receivable Nov",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "29",
    "chartGroup": "Accounts",
    "variableName": "Receivable, Dec",
    "DataPoint": "Accounts Receivable Dec",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(receivable) AS result FROM rental_accounts WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "30",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Jan",
    "DataPoint": "Accounts Overdue Jan",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "31",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Feb",
    "DataPoint": "Accounts Overdue Feb",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "32",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Mar",
    "DataPoint": "Accounts Overdue Mar",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "33",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Apr",
    "DataPoint": "Accounts Overdue Apr",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "34",
    "chartGroup": "Accounts",
    "variableName": "Overdue, May",
    "DataPoint": "Accounts Overdue May",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "35",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Jun",
    "DataPoint": "Accounts Overdue Jun",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "36",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Jul",
    "DataPoint": "Accounts Overdue Jul",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "37",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Aug",
    "DataPoint": "Accounts Overdue Aug",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "38",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Sep",
    "DataPoint": "Accounts Overdue Sep",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "39",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Oct",
    "DataPoint": "Accounts Overdue Oct",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "40",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Nov",
    "DataPoint": "Accounts Overdue Nov",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "41",
    "chartGroup": "Accounts",
    "variableName": "Overdue, Dec",
    "DataPoint": "Accounts Overdue Dec",
    "serverName": "POR",
    "tableName": "rental_accounts",
    "productionSqlExpression": "SELECT SUM(overdue) AS result FROM rental_accounts WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "Accounts Chart",
    "axisStep": null
  },
  {
    "rowId": "42",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Jan",
    "DataPoint": "Customer Metrics New Jan",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "43",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Feb",
    "DataPoint": "Customer Metrics New Feb",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "44",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Mar",
    "DataPoint": "Customer Metrics New Mar",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "45",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Apr",
    "DataPoint": "Customer Metrics New Apr",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "46",
    "chartGroup": "Customer Metrics",
    "variableName": "New, May",
    "DataPoint": "Customer Metrics New May",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "47",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Jun",
    "DataPoint": "Customer Metrics New Jun",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "48",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Jul",
    "DataPoint": "Customer Metrics New Jul",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "49",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Aug",
    "DataPoint": "Customer Metrics New Aug",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "50",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Sep",
    "DataPoint": "Customer Metrics New Sep",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "51",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Oct",
    "DataPoint": "Customer Metrics New Oct",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "52",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Nov",
    "DataPoint": "Customer Metrics New Nov",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "53",
    "chartGroup": "Customer Metrics",
    "variableName": "New, Dec",
    "DataPoint": "Customer Metrics New Dec",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(new) AS result FROM rental_customers WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "54",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Jan",
    "DataPoint": "Customer Metrics Prospects Jan",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "55",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Feb",
    "DataPoint": "Customer Metrics Prospects Feb",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "56",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Mar",
    "DataPoint": "Customer Metrics Prospects Mar",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "57",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Apr",
    "DataPoint": "Customer Metrics Prospects Apr",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "58",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, May",
    "DataPoint": "Customer Metrics Prospects May",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "59",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Jun",
    "DataPoint": "Customer Metrics Prospects Jun",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "60",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Jul",
    "DataPoint": "Customer Metrics Prospects Jul",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "61",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Aug",
    "DataPoint": "Customer Metrics Prospects Aug",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "62",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Sep",
    "DataPoint": "Customer Metrics Prospects Sep",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "63",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Oct",
    "DataPoint": "Customer Metrics Prospects Oct",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "64",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Nov",
    "DataPoint": "Customer Metrics Prospects Nov",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "65",
    "chartGroup": "Customer Metrics",
    "variableName": "Prospects, Dec",
    "DataPoint": "Customer Metrics Prospects Dec",
    "serverName": "POR",
    "tableName": "rental_customers",
    "productionSqlExpression": "SELECT SUM(prospects) AS result FROM rental_customers WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "Customer Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "66",
    "chartGroup": "Daily Orders",
    "variableName": "Orders, Today",
    "DataPoint": "Daily Orders Orders Today",
    "serverName": "P21",
    "tableName": "daily_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM daily_orders WHERE day_label = 'Today';",
    "calculationType": "SUM",
    "chartName": "Daily Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "67",
    "chartGroup": "Daily Orders",
    "variableName": "Orders, Today-1",
    "DataPoint": "Daily Orders Orders Today-1",
    "serverName": "P21",
    "tableName": "daily_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM daily_orders WHERE day_label = 'Today-1';",
    "calculationType": "SUM",
    "chartName": "Daily Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "68",
    "chartGroup": "Daily Orders",
    "variableName": "Orders, Today-2",
    "DataPoint": "Daily Orders Orders Today-2",
    "serverName": "P21",
    "tableName": "daily_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM daily_orders WHERE day_label = 'Today-2';",
    "calculationType": "SUM",
    "chartName": "Daily Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "69",
    "chartGroup": "Daily Orders",
    "variableName": "Orders, Today-3",
    "DataPoint": "Daily Orders Orders Today-3",
    "serverName": "P21",
    "tableName": "daily_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM daily_orders WHERE day_label = 'Today-3';",
    "calculationType": "SUM",
    "chartName": "Daily Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "70",
    "chartGroup": "Daily Orders",
    "variableName": "Orders, Today-4",
    "DataPoint": "Daily Orders Orders Today-4",
    "serverName": "P21",
    "tableName": "daily_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM daily_orders WHERE day_label = 'Today-4';",
    "calculationType": "SUM",
    "chartName": "Daily Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "71",
    "chartGroup": "Daily Orders",
    "variableName": "Orders, Today-5",
    "DataPoint": "Daily Orders Orders Today-5",
    "serverName": "P21",
    "tableName": "daily_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM daily_orders WHERE day_label = 'Today-5';",
    "calculationType": "SUM",
    "chartName": "Daily Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "72",
    "chartGroup": "Daily Orders",
    "variableName": "Orders, Today-6",
    "DataPoint": "Daily Orders Orders Today-6",
    "serverName": "P21",
    "tableName": "daily_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM daily_orders WHERE day_label = 'Today-6';",
    "calculationType": "SUM",
    "chartName": "Daily Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "73",
    "chartGroup": "Historical Data",
    "variableName": "P21, Jan",
    "DataPoint": "Historical Data P21 Jan",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "74",
    "chartGroup": "Historical Data",
    "variableName": "P21, Feb",
    "DataPoint": "Historical Data P21 Feb",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "75",
    "chartGroup": "Historical Data",
    "variableName": "P21, Mar",
    "DataPoint": "Historical Data P21 Mar",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "76",
    "chartGroup": "Historical Data",
    "variableName": "P21, Apr",
    "DataPoint": "Historical Data P21 Apr",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "77",
    "chartGroup": "Historical Data",
    "variableName": "P21, May",
    "DataPoint": "Historical Data P21 May",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "78",
    "chartGroup": "Historical Data",
    "variableName": "P21, Jun",
    "DataPoint": "Historical Data P21 Jun",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "79",
    "chartGroup": "Historical Data",
    "variableName": "P21, Jul",
    "DataPoint": "Historical Data P21 Jul",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "80",
    "chartGroup": "Historical Data",
    "variableName": "P21, Aug",
    "DataPoint": "Historical Data P21 Aug",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "81",
    "chartGroup": "Historical Data",
    "variableName": "P21, Sep",
    "DataPoint": "Historical Data P21 Sep",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "82",
    "chartGroup": "Historical Data",
    "variableName": "P21, Oct",
    "DataPoint": "Historical Data P21 Oct",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "83",
    "chartGroup": "Historical Data",
    "variableName": "P21, Nov",
    "DataPoint": "Historical Data P21 Nov",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "84",
    "chartGroup": "Historical Data",
    "variableName": "P21, Dec",
    "DataPoint": "Historical Data P21 Dec",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(p21) AS result FROM historical_data WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "85",
    "chartGroup": "Historical Data",
    "variableName": "POR, Jan",
    "DataPoint": "Historical Data POR Jan",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "86",
    "chartGroup": "Historical Data",
    "variableName": "POR, Feb",
    "DataPoint": "Historical Data POR Feb",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "87",
    "chartGroup": "Historical Data",
    "variableName": "POR, Mar",
    "DataPoint": "Historical Data POR Mar",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "88",
    "chartGroup": "Historical Data",
    "variableName": "POR, Apr",
    "DataPoint": "Historical Data POR Apr",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "89",
    "chartGroup": "Historical Data",
    "variableName": "POR, May",
    "DataPoint": "Historical Data POR May",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "90",
    "chartGroup": "Historical Data",
    "variableName": "POR, Jun",
    "DataPoint": "Historical Data POR Jun",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "91",
    "chartGroup": "Historical Data",
    "variableName": "POR, Jul",
    "DataPoint": "Historical Data POR Jul",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "92",
    "chartGroup": "Historical Data",
    "variableName": "POR, Aug",
    "DataPoint": "Historical Data POR Aug",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "93",
    "chartGroup": "Historical Data",
    "variableName": "POR, Sep",
    "DataPoint": "Historical Data POR Sep",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "94",
    "chartGroup": "Historical Data",
    "variableName": "POR, Oct",
    "DataPoint": "Historical Data POR Oct",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "95",
    "chartGroup": "Historical Data",
    "variableName": "POR, Nov",
    "DataPoint": "Historical Data POR Nov",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "96",
    "chartGroup": "Historical Data",
    "variableName": "POR, Dec",
    "DataPoint": "Historical Data POR Dec",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(por) AS result FROM historical_data WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "97",
    "chartGroup": "Historical Data",
    "variableName": "Total, Jan",
    "DataPoint": "Historical Data Total Jan",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "98",
    "chartGroup": "Historical Data",
    "variableName": "Total, Feb",
    "DataPoint": "Historical Data Total Feb",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "99",
    "chartGroup": "Historical Data",
    "variableName": "Total, Mar",
    "DataPoint": "Historical Data Total Mar",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "100",
    "chartGroup": "Historical Data",
    "variableName": "Total, Apr",
    "DataPoint": "Historical Data Total Apr",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "101",
    "chartGroup": "Historical Data",
    "variableName": "Total, May",
    "DataPoint": "Historical Data Total May",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "102",
    "chartGroup": "Historical Data",
    "variableName": "Total, Jun",
    "DataPoint": "Historical Data Total Jun",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "103",
    "chartGroup": "Historical Data",
    "variableName": "Total, Jul",
    "DataPoint": "Historical Data Total Jul",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "104",
    "chartGroup": "Historical Data",
    "variableName": "Total, Aug",
    "DataPoint": "Historical Data Total Aug",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "105",
    "chartGroup": "Historical Data",
    "variableName": "Total, Sep",
    "DataPoint": "Historical Data Total Sep",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "106",
    "chartGroup": "Historical Data",
    "variableName": "Total, Oct",
    "DataPoint": "Historical Data Total Oct",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "107",
    "chartGroup": "Historical Data",
    "variableName": "Total, Nov",
    "DataPoint": "Historical Data Total Nov",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "108",
    "chartGroup": "Historical Data",
    "variableName": "Total, Dec",
    "DataPoint": "Historical Data Total Dec",
    "serverName": "P21",
    "tableName": "historical_data",
    "productionSqlExpression": "SELECT SUM(total) AS result FROM historical_data WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "Historical Data Chart",
    "axisStep": null
  },
  {
    "rowId": "109",
    "chartGroup": "Inventory",
    "variableName": "In Stock, 100",
    "DataPoint": "Inventory In Stock Dept 100",
    "serverName": "POR",
    "tableName": "rental_inventory",
    "productionSqlExpression": "SELECT SUM(in_stock) AS result FROM rental_inventory WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Inventory Chart",
    "axisStep": null
  },
  {
    "rowId": "110",
    "chartGroup": "Inventory",
    "variableName": "In Stock, 101",
    "DataPoint": "Inventory In Stock Dept 101",
    "serverName": "POR",
    "tableName": "rental_inventory",
    "productionSqlExpression": "SELECT SUM(in_stock) AS result FROM rental_inventory WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Inventory Chart",
    "axisStep": null
  },
  {
    "rowId": "111",
    "chartGroup": "Inventory",
    "variableName": "In Stock, 102",
    "DataPoint": "Inventory In Stock Dept 102",
    "serverName": "POR",
    "tableName": "rental_inventory",
    "productionSqlExpression": "SELECT SUM(in_stock) AS result FROM rental_inventory WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Inventory Chart",
    "axisStep": null
  },
  {
    "rowId": "112",
    "chartGroup": "Inventory",
    "variableName": "In Stock, 207",
    "DataPoint": "Inventory In Stock Dept 207",
    "serverName": "POR",
    "tableName": "rental_inventory",
    "productionSqlExpression": "SELECT SUM(in_stock) AS result FROM rental_inventory WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Inventory Chart",
    "axisStep": null
  },
  {
    "rowId": "113",
    "chartGroup": "Inventory",
    "variableName": "On Order, 100",
    "DataPoint": "Inventory On Order Dept 100",
    "serverName": "POR",
    "tableName": "rental_inventory",
    "productionSqlExpression": "SELECT SUM(on_order) AS result FROM rental_inventory WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Inventory Chart",
    "axisStep": null
  },
  {
    "rowId": "114",
    "chartGroup": "Inventory",
    "variableName": "On Order, 101",
    "DataPoint": "Inventory On Order Dept 101",
    "serverName": "POR",
    "tableName": "rental_inventory",
    "productionSqlExpression": "SELECT SUM(on_order) AS result FROM rental_inventory WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Inventory Chart",
    "axisStep": null
  },
  {
    "rowId": "115",
    "chartGroup": "Inventory",
    "variableName": "On Order, 102",
    "DataPoint": "Inventory On Order Dept 102",
    "serverName": "POR",
    "tableName": "rental_inventory",
    "productionSqlExpression": "SELECT SUM(on_order) AS result FROM rental_inventory WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Inventory Chart",
    "axisStep": null
  },
  {
    "rowId": "116",
    "chartGroup": "Inventory",
    "variableName": "On Order, 207",
    "DataPoint": "Inventory On Order Dept 207",
    "serverName": "POR",
    "tableName": "rental_inventory",
    "productionSqlExpression": "SELECT SUM(on_order) AS result FROM rental_inventory WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Inventory Chart",
    "axisStep": null
  },
  {
    "rowId": "117",
    "chartGroup": "Key Metrics",
    "variableName": "Total Orders",
    "DataPoint": "Key Metrics Total Orders Overview",
    "serverName": "P21",
    "tableName": "key_metrics",
    "productionSqlExpression": "SELECT SUM(total_orders) AS result FROM key_metrics WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Key Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "118",
    "chartGroup": "Key Metrics",
    "variableName": "Open Orders (/day)",
    "DataPoint": "Key Metrics Open Orders (/day) Overview",
    "serverName": "P21",
    "tableName": "key_metrics",
    "productionSqlExpression": "SELECT SUM(open_orders__per_day) AS result FROM key_metrics WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Key Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "119",
    "chartGroup": "Key Metrics",
    "variableName": "All Open Orders",
    "DataPoint": "Key Metrics All Open Orders Overview",
    "serverName": "P21",
    "tableName": "key_metrics",
    "productionSqlExpression": "SELECT SUM(all_open_orders) AS result FROM key_metrics WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Key Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "120",
    "chartGroup": "Key Metrics",
    "variableName": "Daily Revenue",
    "DataPoint": "Key Metrics Daily Revenue Overview",
    "serverName": "P21",
    "tableName": "key_metrics",
    "productionSqlExpression": "SELECT SUM(daily_revenue) AS result FROM key_metrics WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Key Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "121",
    "chartGroup": "Key Metrics",
    "variableName": "Open Invoices",
    "DataPoint": "Key Metrics Open Invoices Overview",
    "serverName": "P21",
    "tableName": "key_metrics",
    "productionSqlExpression": "SELECT SUM(open_invoices) AS result FROM key_metrics WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Key Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "122",
    "chartGroup": "Key Metrics",
    "variableName": "OrdersBackloged",
    "DataPoint": "Key Metrics OrdersBackloged Overview",
    "serverName": "P21",
    "tableName": "key_metrics",
    "productionSqlExpression": "SELECT SUM(ordersbackloged) AS result FROM key_metrics WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Key Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "123",
    "chartGroup": "Key Metrics",
    "variableName": "Total Sales Monthly",
    "DataPoint": "Key Metrics Total Sales Monthly Overview",
    "serverName": "P21",
    "tableName": "key_metrics",
    "productionSqlExpression": "SELECT SUM(total_sales_monthly) AS result FROM key_metrics WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Key Metrics Chart",
    "axisStep": null
  },
  {
    "rowId": "124",
    "chartGroup": "Site Distribution",
    "variableName": "Value",
    "DataPoint": "Site Distribution Value Columbus",
    "serverName": "P21",
    "tableName": "site_distribution",
    "productionSqlExpression": "SELECT SUM(value) AS result FROM site_distribution WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Site Distribution Chart",
    "axisStep": null
  },
  {
    "rowId": "125",
    "chartGroup": "Site Distribution",
    "variableName": "Value",
    "DataPoint": "Site Distribution Value Addison",
    "serverName": "P21",
    "tableName": "site_distribution",
    "productionSqlExpression": "SELECT SUM(value) AS result FROM site_distribution WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Site Distribution Chart",
    "axisStep": null
  },
  {
    "rowId": "126",
    "chartGroup": "Site Distribution",
    "variableName": "Value",
    "DataPoint": "Site Distribution Value Lake City",
    "serverName": "P21",
    "tableName": "site_distribution",
    "productionSqlExpression": "SELECT SUM(value) AS result FROM site_distribution WHERE 1=1;",
    "calculationType": "SUM",
    "chartName": "Site Distribution Chart",
    "axisStep": null
  },
  {
    "rowId": "127",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Jan",
    "DataPoint": "POR Overview New Rentals Jan",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "128",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Feb",
    "DataPoint": "POR Overview New Rentals Feb",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "129",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Mar",
    "DataPoint": "POR Overview New Rentals Mar",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "130",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Apr",
    "DataPoint": "POR Overview New Rentals Apr",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "131",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, May",
    "DataPoint": "POR Overview New Rentals May",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "132",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Jun",
    "DataPoint": "POR Overview New Rentals Jun",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "133",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Jul",
    "DataPoint": "POR Overview New Rentals Jul",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "134",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Aug",
    "DataPoint": "POR Overview New Rentals Aug",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "135",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Sep",
    "DataPoint": "POR Overview New Rentals Sep",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "136",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Oct",
    "DataPoint": "POR Overview New Rentals Oct",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "137",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Nov",
    "DataPoint": "POR Overview New Rentals Nov",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "138",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals, Dec",
    "DataPoint": "POR Overview New Rentals Dec",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(new_rentals) AS result FROM rental_overview WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "139",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Jan",
    "DataPoint": "POR Overview Open Rentals Jan",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "140",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Feb",
    "DataPoint": "POR Overview Open Rentals Feb",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "141",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Mar",
    "DataPoint": "POR Overview Open Rentals Mar",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "142",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Apr",
    "DataPoint": "POR Overview Open Rentals Apr",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "143",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, May",
    "DataPoint": "POR Overview Open Rentals May",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "144",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Jun",
    "DataPoint": "POR Overview Open Rentals Jun",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "145",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Jul",
    "DataPoint": "POR Overview Open Rentals Jul",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "146",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Aug",
    "DataPoint": "POR Overview Open Rentals Aug",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "147",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Sep",
    "DataPoint": "POR Overview Open Rentals Sep",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "148",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Oct",
    "DataPoint": "POR Overview Open Rentals Oct",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "149",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Nov",
    "DataPoint": "POR Overview Open Rentals Nov",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "150",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals, Dec",
    "DataPoint": "POR Overview Open Rentals Dec",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(open_rentals) AS result FROM rental_overview WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "151",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Jan",
    "DataPoint": "POR Overview Rental Value Jan",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "152",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Feb",
    "DataPoint": "POR Overview Rental Value Feb",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "153",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Mar",
    "DataPoint": "POR Overview Rental Value Mar",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "154",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Apr",
    "DataPoint": "POR Overview Rental Value Apr",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "155",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, May",
    "DataPoint": "POR Overview Rental Value May",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "156",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Jun",
    "DataPoint": "POR Overview Rental Value Jun",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "157",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Jul",
    "DataPoint": "POR Overview Rental Value Jul",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "158",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Aug",
    "DataPoint": "POR Overview Rental Value Aug",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "159",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Sep",
    "DataPoint": "POR Overview Rental Value Sep",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "160",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Oct",
    "DataPoint": "POR Overview Rental Value Oct",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "161",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Nov",
    "DataPoint": "POR Overview Rental Value Nov",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "162",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value, Dec",
    "DataPoint": "POR Overview Rental Value Dec",
    "serverName": "POR",
    "tableName": "rental_overview",
    "productionSqlExpression": "SELECT SUM(rental_value) AS result FROM rental_overview WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "POR Overview Chart",
    "axisStep": null
  },
  {
    "rowId": "163",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Jan",
    "DataPoint": "Web Orders Orders Jan",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Jan';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "164",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Feb",
    "DataPoint": "Web Orders Orders Feb",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Feb';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "165",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Mar",
    "DataPoint": "Web Orders Orders Mar",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Mar';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "166",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Apr",
    "DataPoint": "Web Orders Orders Apr",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Apr';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "167",
    "chartGroup": "Web Orders",
    "variableName": "Orders, May",
    "DataPoint": "Web Orders Orders May",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'May';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "168",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Jun",
    "DataPoint": "Web Orders Orders Jun",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Jun';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "169",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Jul",
    "DataPoint": "Web Orders Orders Jul",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Jul';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "170",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Aug",
    "DataPoint": "Web Orders Orders Aug",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Aug';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "171",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Sep",
    "DataPoint": "Web Orders Orders Sep",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Sep';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "172",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Oct",
    "DataPoint": "Web Orders Orders Oct",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Oct';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "173",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Nov",
    "DataPoint": "Web Orders Orders Nov",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Nov';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  },
  {
    "rowId": "174",
    "chartGroup": "Web Orders",
    "variableName": "Orders, Dec",
    "DataPoint": "Web Orders Orders Dec",
    "serverName": "POR",
    "tableName": "rental_web_orders",
    "productionSqlExpression": "SELECT SUM(orders) AS result FROM rental_web_orders WHERE month = 'Dec';",
    "calculationType": "SUM",
    "chartName": "Web Orders Chart",
    "axisStep": null
  }
];
