import type { ChartDataRow } from './types';

export type SourceDataDefinition = Omit<ChartDataRow, 'id' | 'value' | 'lastUpdated'>;

export const singleSourceData: SourceDataDefinition[] = [
  {
    "rowId": "1",
    "chartGroup": "AR Aging",
    "variableName": "Open AR Amount",
    "DataPoint": "AR Aging - Open AR Amount - Current",
    "serverName": "P21",
    "tableName": "dbo.ARINV",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen), 0) AS value FROM dbo.p21_view_GetOpenAR_dtl WHERE DATEDIFF(day, net_due_date, GETDATE()) <= 0;",
    "calculationType": "SUM",
    "chartName": "AR Aging",
    "axisStep": "Current"
  },
  {
    "rowId": "2",
    "chartGroup": "AR Aging",
    "variableName": "Open AR Amount", 
    "DataPoint": "AR Aging - Open AR Amount - 1-30 days past due", 
    "serverName": "P21",
    "tableName": "dbo.ARINV", 
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen), 0) AS value FROM dbo.p21_view_GetOpenAR_dtl WHERE DATEDIFF(day, net_due_date, GETDATE()) BETWEEN 1 AND 30;",
    "calculationType": "SUM", 
    "chartName": "AR Aging",
    "axisStep": "1-30 days"
  },
  {
    "rowId": "3",
    "chartGroup": "AR Aging",
    "variableName": "Open AR Amount", 
    "DataPoint": "AR Aging - Open AR Amount - 31-60 days past due", 
    "serverName": "P21",
    "tableName": "dbo.ARINV", 
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen), 0) AS value FROM dbo.p21_view_GetOpenAR_dtl WHERE DATEDIFF(day, net_due_date, GETDATE()) BETWEEN 31 AND 60;", 
    "calculationType": "SUM",
    "chartName": "AR Aging",
    "axisStep": "31-60 days"
  },
  {
    "rowId": "4",
    "chartGroup": "AR Aging",
    "variableName": "Open AR Amount", 
    "DataPoint": "AR Aging - Open AR Amount - 61-90 days past due", 
    "serverName": "P21",
    "tableName": "dbo.ARINV", 
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen), 0) AS value FROM dbo.p21_view_GetOpenAR_dtl WHERE DATEDIFF(day, net_due_date, GETDATE()) BETWEEN 61 AND 90;", 
    "calculationType": "SUM", 
    "chartName": "AR Aging",
    "axisStep": "61-90 days"
  },
  {
    "rowId": "5",
    "chartGroup": "AR Aging",
    "variableName": "Open AR Amount",
    "DataPoint": "AR Aging - Open AR Amount - 91+ days past due",
    "serverName": "P21",
    "tableName": "dbo.ARINV", 
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen), 0) AS value FROM dbo.p21_view_GetOpenAR_dtl WHERE DATEDIFF(day, net_due_date, GETDATE()) > 90;", 
    "calculationType": "SUM", 
    "chartName": "AR Aging",
    "axisStep": "91+ days"
  },
  {
    "rowId": "6",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -11",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-11,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-10,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -11"
  },
  {
    "rowId": "7",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -10",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-10,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-9,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -10"
  },
  {
    "rowId": "8",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -9",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-9,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-8,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -9"
  },
  {
    "rowId": "9",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -8",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-8,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-7,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -8"
  },
  {
    "rowId": "10",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -7",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-7,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-6,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -7"
  },
  {
    "rowId": "11",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -6",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-6,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-5,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -6"
  },
  {
    "rowId": "12",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -5",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-5,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-4,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -5"
  },
  {
    "rowId": "13",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -4",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-4,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-3,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -4"
  },
  {
    "rowId": "14",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -3",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-3,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-2,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -3"
  },
  {
    "rowId": "15",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -2",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-2,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-1,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -2"
  },
  {
    "rowId": "16",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Month -1",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-1,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -1"
  },
  {
    "rowId": "17",
    "chartGroup": "Accounts",
    "variableName": "Receivables",
    "DataPoint": "Accounts - Receivables - Current",
    "serverName": "P21",
    "tableName": "dbo.p21_view_GetOpenAR_dtl",
    "productionSqlExpression": "SELECT ISNULL(SUM(ArAmountOpen),0) AS value FROM dbo.p21_view_GetOpenAR_dtl WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())+1,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -0"
  },
  {
    "rowId": "18",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -11",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-11,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-10,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -11"
  },
  {
    "rowId": "19",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -10",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-10,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-9,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -10"
  },
  {
    "rowId": "20",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -9",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-9,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-8,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -9"
  },
  {
    "rowId": "21",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -8",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-8,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-7,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -8"
  },
  {
    "rowId": "22",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -7",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-7,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-6,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -7"
  },
  {
    "rowId": "23",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -6",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-6,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-5,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -6"
  },
  {
    "rowId": "24",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -5",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-5,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-4,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -5"
  },
  {
    "rowId": "25",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -4",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-4,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-3,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -4"
  },
  {
    "rowId": "26",
    "chartGroup": "Accounts",
    "variableName": "Payables",  
    "DataPoint": "Accounts - Payables - Month -3",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-3,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-2,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -3"
  },
  {
    "rowId": "27",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -2",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-2,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-1,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -2"
  },
  {
    "rowId": "28",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Month -1",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-1,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0);",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -1"
  },
  {
    "rowId": "29",
    "chartGroup": "Accounts",
    "variableName": "Payables",
    "DataPoint": "Accounts - Payables - Current",
    "serverName": "P21",
    "tableName": "dbo.p21_view_apinv_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(open_amount),0) AS value FROM dbo.p21_view_apinv_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())+1,0);",
    "calculationType": "SUM",
    "chartName": "Accounts",  
    "axisStep": "Month -0"
  },
  {
    "rowId": "30",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -11",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-11,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-10,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -11"
  },
  {
    "rowId": "31",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -10",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-10,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-9,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -10"
  },
  {
    "rowId": "32",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -9",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-9,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-8,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -9"
  },
  {
    "rowId": "33",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -8",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-8,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-7,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -8"
  },
  {
    "rowId": "34",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -7",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-7,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-6,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -7"
  },
  {
    "rowId": "35",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -6",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-6,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-5,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -6"
  },
  {
    "rowId": "36",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -5",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-5,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-4,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -5"
  },
  {
    "rowId": "37",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -4",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-4,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-3,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -4"
  },
  {
    "rowId": "38",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -3",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-3,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-2,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -3"
  },
  {
    "rowId": "39",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -2",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-2,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-1,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -2"
  },
  {
    "rowId": "40",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Month -1",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-1,0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -1"
  },
  {
    "rowId": "41",
    "chartGroup": "Accounts",
    "variableName": "Overdue",
    "DataPoint": "Accounts - Overdue - Current",
    "serverName": "P21",
    "tableName": "dbo.invoice_hdr",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount - amount_paid),0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0) AND invoice_date < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())+1,0) AND paid_in_full_flag <> 'Y' AND net_due_date < GETDATE();",
    "calculationType": "SUM",
    "chartName": "Accounts",
    "axisStep": "Month -0"
  },
  {
    "rowId": "42",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -11",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -12, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -11, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -11"
  },
  {
    "rowId": "43",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -10",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -11, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -10, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -10"
  },
  {
    "rowId": "44",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -9",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -10, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -9, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -9"
  },
  {
    "rowId": "45",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -8",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -9, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -8, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -8"
  },
  {
    "rowId": "46",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -7",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -8, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -7, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -7"
  },
  {
    "rowId": "47",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -6",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -7, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -6, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -6"
  },
  {
    "rowId": "48",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -5",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -6, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -5, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -5"
  },
  {
    "rowId": "49",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -4",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -5, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -4, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -4"
  },
  {
    "rowId": "50",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -3",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -4, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -3, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -3"
  },
  {
    "rowId": "51",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -2",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -3, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -2, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -2"
  },
  {
    "rowId": "52",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Month -1",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -2, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -1, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -1"
  },
  {
    "rowId": "53",
    "chartGroup": "Customer Metrics",
    "variableName": "customer_metrics_prospects",
    "DataPoint": "Customer Metrics - Prospects - Current",
    "serverName": "P21",
    "tableName": "dbo.customer",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE customer_type_cd = 1203 AND date_created >= DATEADD(month, -1, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, 0, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -0"
  },
  { "rowId": "54",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -11",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WHERE date_created >= DATEADD(month, -12, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -11, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -11"
  },
  { "rowId": "55",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -10",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE date_created >= DATEADD(month, -11, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -10, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -10"
  },
  { "rowId": "56",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -9",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WHERE date_created >= DATEADD(month, -10, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -9, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -9"
  },
  { "rowId": "57",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -8",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE date_created >= DATEADD(month, -9, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -8, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -8"
  },
  { "rowId": "58",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -7",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WHERE date_created >= DATEADD(month, -7, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -6, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -7"
  },
  { "rowId": "59",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -6",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE date_created >= DATEADD(month, -5, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -4, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -6"
  },
  { "rowId": "60",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -5",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WHERE date_created >= DATEADD(month, -4, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -3, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -5"
  },
  { "rowId": "61",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -4",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE date_created >= DATEADD(month, -3, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -2 DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -4"
  },
  { "rowId": "62",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -3",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WHERE date_created >= DATEADD(month, -2, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -1, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -3"
  },
  { "rowId": "63",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -2",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE date_created >= DATEADD(month, -1, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -0, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -2"
  },
  { "rowId": "64",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month -1",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WHERE date_created >= DATEADD(month, -2, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -1, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -1"
  },
  { "rowId": "65",
    "chartGroup": "Customer Metrics",
    "variableName": "New Customers",
    "DataPoint": "Customer Metrics - New Customers - Month Current",
    "serverName": "P21",
    "tableName": "dbo.Customers",
    "productionSqlExpression": "SELECT COUNT(customer_id) AS value FROM dbo.customer WITH (NOLOCK) WHERE date_created >= DATEADD(month, -1, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) AND date_created < DATEADD(month, -0, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0));",
    "calculationType": "COUNT",
    "chartName": "Customer Metrics",
    "axisStep": "Month -0"
  },
  
  {
    "rowId": "66",
    "chartGroup": "Daily Orders",
    "variableName": "orders",
    "DataPoint": "Daily Orders - Orders - Today-6",
    "serverName": "P21",
    "tableName": "dbo.p21_view_support_sql_salesorder_oe_hdr",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.p21_view_support_sql_salesorder_oe_hdr WHERE order_date >= DATEADD(DAY, -6, CAST(GETDATE() AS DATE)) AND order_date < DATEADD(DAY, -5, CAST(GETDATE() AS DATE))",
    "calculationType": "COUNT",
    "chartName": "Daily Orders",
    "axisStep": "Today-6"
  },
  {
    "rowId": "67",
    "chartGroup": "Daily Orders",
    "variableName": "orders",
    "DataPoint": "Daily Orders - Orders - Today-5",
    "serverName": "P21",
    "tableName": "dbo.p21_view_support_sql_salesorder_oe_hdr",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.p21_view_support_sql_salesorder_oe_hdr WHERE order_date >= DATEADD(DAY, -5, CAST(GETDATE() AS DATE)) AND order_date < DATEADD(DAY, -4, CAST(GETDATE() AS DATE))",
    "calculationType": "COUNT",
    "chartName": "Daily Orders",
    "axisStep": "Today-5"
  },
  {
    "rowId": "68",
    "chartGroup": "Daily Orders",
    "variableName": "orders",
    "DataPoint": "Daily Orders - Orders - Today-4",
    "serverName": "P21",
    "tableName": "dbo.p21_view_support_sql_salesorder_oe_hdr",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.p21_view_support_sql_salesorder_oe_hdr WHERE order_date >= DATEADD(DAY, -4, CAST(GETDATE() AS DATE)) AND order_date < DATEADD(DAY, -3, CAST(GETDATE() AS DATE))",
    "calculationType": "COUNT",
    "chartName": "Daily Orders",
    "axisStep": "Today-4"
  },
  {
    "rowId": "69",
    "chartGroup": "Daily Orders",
    "variableName": "orders",
    "DataPoint": "Daily Orders - Orders - Today-3",
    "serverName": "P21",
    "tableName": "dbo.p21_view_support_sql_salesorder_oe_hdr",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.p21_view_support_sql_salesorder_oe_hdr WHERE order_date >= DATEADD(DAY, -3, CAST(GETDATE() AS DATE)) AND order_date < DATEADD(DAY, -2, CAST(GETDATE() AS DATE))",
    "calculationType": "COUNT",
    "chartName": "Daily Orders",
    "axisStep": "Today-3"
  },
  {
    "rowId": "70",
    "chartGroup": "Daily Orders",
    "variableName": "orders",
    "DataPoint": "Daily Orders - Orders - Today-2",
    "serverName": "P21",
    "tableName": "dbo.p21_view_support_sql_salesorder_oe_hdr",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.p21_view_support_sql_salesorder_oe_hdr WHERE order_date >= DATEADD(DAY, -2, CAST(GETDATE() AS DATE)) AND order_date < DATEADD(DAY, -1, CAST(GETDATE() AS DATE))",
    "calculationType": "COUNT",
    "chartName": "Daily Orders",
    "axisStep": "Today-2"
  },
  {
    "rowId": "71",
    "chartGroup": "Daily Orders",
    "variableName": "orders",
    "DataPoint": "Daily Orders - Orders - Today-1",
    "serverName": "P21",
    "tableName": "dbo.p21_view_support_sql_salesorder_oe_hdr",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.p21_view_support_sql_salesorder_oe_hdr WHERE order_date >= DATEADD(DAY, -1, CAST(GETDATE() AS DATE)) AND order_date < CAST(GETDATE() AS DATE)",
    "calculationType": "COUNT",
    "chartName": "Daily Orders",
    "axisStep": "Today-1"
  },
  {
    "rowId": "72",
    "chartGroup": "Daily Orders",
    "variableName": "orders",
    "DataPoint": "Daily Orders - Orders - Today",
    "serverName": "P21",
    "tableName": "dbo.p21_view_support_sql_salesorder_oe_hdr",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.p21_view_support_sql_salesorder_oe_hdr WHERE order_date >= CAST(GETDATE() AS DATE)",
    "calculationType": "COUNT",
    "chartName": "Daily Orders",
    "axisStep": "Today"
  },
  {
    "rowId": "73",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -11",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-11,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-10,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -11"
  },
  {
    "rowId": "74",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -10",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-10,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-9,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -10"
  },
  {
    "rowId": "75",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -9",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-9,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-8,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -9"
  },
  {
    "rowId": "76",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -8",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-8,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-7,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -8"
  },
  {
    "rowId": "77",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -7",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-7,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-6,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -7"
  },
  {
    "rowId": "78",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -6",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-6,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-5,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -6"
  },
  {
    "rowId": "79",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -5",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-5,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-4,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -5"
  },
  {
    "rowId": "80",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -4",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-4,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-3,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -4"
  },
  {
    "rowId": "81",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -3",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-3,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-2,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -3"
  },
  {
    "rowId": "82",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -2",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-2,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,-1,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -2"
  },
  {
    "rowId": "83",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Month -1",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,-1,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,0,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -1"
  },
  {
    "rowId": "84",
    "chartGroup": "Historical Data",
    "variableName": "Sales P21",
    "DataPoint": "Historical Data - Sales P21 - Current",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,0,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,1,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -0"
  },
  { 
    "rowId": "85",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -11",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_amount), 0) AS value FROM dbo.invoice_hdr WITH (NOLOCK) WHERE invoice_date >= DATEADD(DAY,  1, EOMONTH(GETDATE(), -12)) AND invoice_date   <  DATEADD(DAY,  1, EOMONTH(GETDATE(), -11));",    
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -11"
  },
  { 
    "rowId": "86",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -10",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -10, Date())), Month(DateAdd('m', -10, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', -9, Date())), Month(DateAdd('m', -9, Date())), 1);",        
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -10"
  },
  { 
    "rowId": "87",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -9",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -9, Date())), Month(DateAdd('m', -9, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', -8, Date())), Month(DateAdd('m', -8, Date())), 1);",    
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -9"
  },
  { 
    "rowId": "88",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -8",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -8, Date())), Month(DateAdd('m', -8, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', -7, Date())), Month(DateAdd('m', -7, Date())), 1);",      
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -8"
  },
  { "rowId": "89",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month 7",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -7, Date())), Month(DateAdd('m', -7, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', -6, Date())), Month(DateAdd('m', -6, Date())), 1);",    
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month 7"
  },
  { "rowId": "90",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -6",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -6, Date())), Month(DateAdd('m', -6, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', -5, Date())), Month(DateAdd('m', -5, Date())), 1);",  
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -6"
  },
  { "rowId": "91",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -5",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -5, Date())), Month(DateAdd('m', -5, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', -4, Date())), Month(DateAdd('m', -4, Date())), 1);",     
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month-5"
  },
  { "rowId": "92",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -4",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -4, Date())), Month(DateAdd('m', -4, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', -3, Date())), Month(DateAdd('m', -3, Date())), 1);",    
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month 4"
  },
  { "rowId": "93",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -3",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -3, Date())), Month(DateAdd('m', -3, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', -2, Date())), Month(DateAdd('m', -2, Date())), 1);",      
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -3"
  },
  { "rowId": "94",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -2",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -2, Date())), Month(DateAdd('m', -2, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', -1, Date())), Month(DateAdd('m', -1, Date())), 1);",      
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -2"
  },
  { "rowId": "95",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Month -1",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(DateAdd('m', -1, Date())), Month(DateAdd('m', -1, Date())), 1) AND invoice_date < DateSerial(Year(DateAdd('m', 0, Date())), Month(DateAdd('m', 0, Date())), 1);",   
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -1"
  },
  { "rowId": "96",
    "chartGroup": "Historical Data",
    "variableName": "Sales POR",
    "DataPoint": "Historical Data - Sales POR - Current",
    "serverName": "POR",
    "tableName": "SOMAST",
    "productionSqlExpression": "SELECT Nz(SUM(total_amount),0) AS value FROM invoice_hdr WHERE invoice_date >= DateSerial(Year(Date()), Month(Date()), 1) AND invoice_date < DateSerial(Year(DateAdd('m', 1, Date())), Month(DateAdd('m', 1, Date())), 1);",     
    "calculationType": "SUM",
    "chartName": "Historical Data",
    "axisStep": "Month -0"
  },
  { "rowId": "97",
    "chartGroup": "Inventory",
    "variableName": "in_stock",
    "DataPoint": "Inventory - in_stock - Addison 100",
    "serverName": "P21",
    "tableName": "dbo.ICINV",
    "productionSqlExpression":"SELECT COALESCE(SUM(qty_on_hand), 0) AS value FROM inv_loc WITH (NOLOCK) WHERE location_id = 100 AND qty_on_hand > 0;",
    "calculationType": "SUM",
    "chartName": "Inventory",
    "axisStep": "Dept 100"
  },
  { "rowId": "98",
    "chartGroup": "Inventory",
    "variableName": "in_stock",
    "DataPoint": "Inventory - in_stock - Columbus 101",
    "serverName": "P21",
    "tableName": "dbo.ICINV",
    "productionSqlExpression":"SELECT COALESCE(SUM(qty_on_hand), 0) AS value FROM inv_loc WITH (NOLOCK) WHERE location_id = 101 AND qty_on_hand > 0;",
    "calculationType": "SUM",
    "chartName": "Inventory",
    "axisStep": "Dept 101"
  },
  { "rowId": "99",
    "chartGroup": "Inventory",
    "variableName": "in_stock",
    "DataPoint": "Inventory - in_stock - sBlocks 102",
    "serverName": "P21",
    "tableName": "dbo.ICINV",
    "productionSqlExpression":"SELECT COALESCE(SUM(qty_on_hand), 0) AS value FROM inv_loc WITH (NOLOCK) WHERE location_id = 102 AND qty_on_hand > 0;",
    "calculationType": "SUM",
    "chartName": "Inventory",
    "axisStep": "Dept 102"
  },
  { "rowId": "100",
    "chartGroup": "Inventory",
    "variableName": "in_stock",
    "DataPoint": "Inventory - in_stock - LakeCity 107",
    "serverName": "P21",
    "tableName": "dbo.ICINV",
    "productionSqlExpression":"SELECT COALESCE(SUM(qty_on_hand), 0) AS value FROM inv_loc WITH (NOLOCK) WHERE location_id = 107 AND qty_on_hand > 0;",
    "calculationType": "SUM",
    "chartName": "Inventory",
    "axisStep": "Dept 107"
  },
  { "rowId": "101",
    "chartGroup": "Inventory",
    "variableName": "0n_order",
    "DataPoint": "Inventory - 0n_order - Dept 100",
    "serverName": "P21",
    "tableName": "dbo.ICINV",
    "productionSqlExpression": "SELECT COALESCE(SUM(qty_in_transit), 0) AS value FROM inv_loc WITH (NOLOCK) WHERE location_id = 100 AND qty_in_transit > 0;",
    "calculationType": "SUM",
    "chartName": "Inventory",
    "axisStep": "Dept 100"
  },
  { "rowId": "102",
    "chartGroup": "Inventory",
    "variableName": "0n_order",
    "DataPoint": "Inventory - 0n_order - Dept 101",
    "serverName": "P21",
    "tableName": "dbo.ICINV",
    "productionSqlExpression": "SELECT COALESCE(SUM(qty_in_transit), 0) AS value FROM inv_loc WITH (NOLOCK) WHERE location_id = 101 AND qty_in_transit > 0;",
    "calculationType": "SUM",
    "chartName": "Inventory",
    "axisStep": "Dept 101"
  },
  { "rowId": "103",
    "chartGroup": "Inventory",
    "variableName": "0n_order",
    "DataPoint": "Inventory - 0n_order - Dept 102",
    "serverName": "P21",
    "tableName": "dbo.ICINV",
    "productionSqlExpression": "SELECT COALESCE(SUM(qty_in_transit), 0) AS value FROM inv_loc WITH (NOLOCK) WHERE location_id = 102 AND qty_in_transit > 0;",
    "calculationType": "SUM",
    "chartName": "Inventory",
    "axisStep": "Dept 102"
  },
  { "rowId": "104",
    "chartGroup": "Inventory",
    "variableName": "0n_order",
    "DataPoint": "Inventory - 0n_order - Dept 107",
    "serverName": "P21",
    "tableName": "dbo.ICINV",
    "productionSqlExpression": "SELECT COALESCE(SUM(qty_in_transit), 0) AS value FROM inv_loc WITH (NOLOCK) WHERE location_id = 107 AND qty_in_transit > 0;",
    "calculationType": "SUM",
    "chartName": "Inventory",
    "axisStep": "Dept 107"
  },
  { "rowId": "105",
    "chartGroup": "Key Metrics",
    "variableName": "Total_Orders",
    "DataPoint": "Key Metrics - Order_count - Current Week",
    "serverName": "P21",
    "tableName": "dbo.OE_HDR",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.oe_hdr WHERE order_date >= DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0) AND order_date < DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()) + 1, 0);",
    "calculationType": "COUNT",
    "chartName": "Key Metrics",
    "axisStep": "Current Week"
  },
  { "rowId": "106",
    "chartGroup": "Key Metrics",
    "variableName": "Open_Orders",
    "DataPoint": "Key Metrics - Open Orders - All",
    "serverName": "P21",
    "tableName": "dbo.OE_HDR",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.oe_hdr WHERE order_date >= DATEADD(YEAR, -1, GETDATE());",
    "calculationType": "COUNT",
    "chartName": "Key Metrics",
    "axisStep": "Current"
  },
  { "rowId": "107",
    "chartGroup": "Key Metrics",
    "variableName": "Daily_Orders",
    "DataPoint": "Key Metrics - Daily Orders - today",
    "serverName": "P21",
    "tableName": "dbo.OE_HDR",
    "productionSqlExpression": "SELECT COUNT(order_no) AS value FROM dbo.oe_hdr WHERE CAST(order_date AS DATE) = CAST(GETDATE() AS DATE);",
    "calculationType": "COUNT",
    "chartName": "Key Metrics",
    "axisStep": "Today"
  },
  { "rowId": "108",
    "chartGroup": "Key Metrics",
    "variableName": "Open_Invoices",
    "DataPoint": "Key Metrics - Order_count - All",
    "serverName": "P21",
    "tableName": "dbo.OE_HDR",
    "productionSqlExpression": "SELECT COUNT(invoice_no) AS value FROM p21_view_GetOpenAR_dtl WHERE invoice_date >= DATEADD(YEAR, -1, GETDATE()) AND ArAmountOpen > 0;",
    "calculationType": "COUNT",
    "chartName": "Key Metrics",
    "axisStep": "Current"
  },
  { "rowId": "109",
    "chartGroup": "Key Metrics",
    "variableName": "Orders_Backloged",
    "DataPoint": "Key Metrics - Orders Backloged - All",
    "serverName": "P21",
    "tableName": "dbo.OE_HDR",
    "productionSqlExpression": "SELECT COUNT(order_no) AS total_backlog_orders_last_12_months FROM dbo.oe_hdr WHERE order_date >= DATEADD(YEAR, -1, GETDATE()) AND date_order_completed IS NULL;",
    "calculationType": "COUNT",
    "chartName": "Key Metrics",
    "axisStep": "Current"
  },
  { "rowId": "110",
    "chartGroup": "Key Metrics",
    "variableName": "Order_count",
    "DataPoint": "Key Metrics - Order_count - Current Day",
    "serverName": "P21",
    "tableName": "dbo.OE_HDR",
    "productionSqlExpression": "SELECT COUNT(order_no) AS total_new_orders_today FROM dbo.oe_hdr WHERE CAST(order_date AS DATE) = CAST(GETDATE() AS DATE);",
    "calculationType": "COUNT",
    "chartName": "Key Metrics",
    "axisStep": "Current Day"
  },
  { "rowId": "111",
    "chartGroup": "Key Metrics",
    "variableName": "Total_Sales",
    "DataPoint": "Key Metrics - Total Sales - Current Month",
    "serverName": "P21",
    "tableName": "dbo.OE_HDR",
    "productionSqlExpression": "WITH invs AS ( SELECT invoice_no, MAX(invoice_date) AS invoice_date, MAX(total_sales) AS invoice_total FROM p21_sales_history_report_view WITH (NOLOCK) WHERE invoice_date >= DATEADD(MONTH,0,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) AND invoice_date < DATEADD(MONTH,1,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)) GROUP BY invoice_no ) SELECT ISNULL(SUM(invoice_total),0) AS value FROM invs;",
    "calculationType": "SUM",
    "chartName": "Key Metrics",
    "axisStep": "Last 12 Months"
  },
  { "rowId": "112",
    "chartGroup": "Site Distribution",
    "variableName": "Sales_Total_Columbus",
    "DataPoint": "Site Distribution - Sales Total - Columbus",
    "serverName": "P21",
    "tableName": "dbo.SOMAST",
    "productionSqlExpression": "SELECT COUNT(*) AS total_lines, COUNT(DISTINCT invoice_no) AS unique_invoices FROM p21_sales_history_report_view WHERE sales_location_name LIKE '%Columbus%';",
    "calculationType": "SUM",
    "chartName": "Site Distribution",
    "axisStep": "Columbus"
  },
  { "rowId": "113",
    "chartGroup": "Site Distribution",
    "variableName": "Sales_Total_Addison",
    "DataPoint": "Site Distribution - Sales Total - Addison",
    "serverName": "P21",
    "tableName": "dbo.SOMAST",
    "productionSqlExpression": "SELECT COUNT(*) AS total_lines, COUNT(DISTINCT invoice_no) AS unique_invoices FROM p21_sales_history_report_view WHERE sales_location_name LIKE '%Addison%';",
    "calculationType": "SUM",
    "chartName": "Site Distribution", 
    "axisStep": "Addison"
  },
  { "rowId": "114",
    "chartGroup": "Site Distribution",
    "variableName": "Sales_Total_Lake_City",
    "DataPoint": "Site Distribution - Sales Total - Lake City",
    "serverName": "P21",
    "tableName": "dbo.SOMAST",
    "productionSqlExpression": "SELECT COUNT(*) AS total_lines, COUNT(DISTINCT invoice_no) AS unique_invoices FROM p21_sales_history_report_view WHERE sales_location_name LIKE '%Lake City%';",
    "calculationType": "SUM",
    "chartName": "Site Distribution",
    "axisStep": "Lake City"
  },
  {
    "rowId": "115",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -11",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 11, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 10, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -11"
  },
  {
    "rowId": "116",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -10",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 10, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 9, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -10"
  },
  {
    "rowId": "117",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -9",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 9, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 8, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -9"
  },
  {
    "rowId": "118",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -8",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 8, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 7, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -8"
  },
  {
    "rowId": "119",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -7",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 7, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 6, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -7"
  },
  {
    "rowId": "120",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -6",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 6, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 5, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -6"
  },
  {
    "rowId": "121",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -5",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 5, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 4, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -5"
  },
  {
    "rowId": "122",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -4",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 4, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 3, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -4"
  },
  {
    "rowId": "123",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -3",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 3, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 2, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -3"
  },
  {
    "rowId": "124",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -2",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 2, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 1, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -2"
  },
  {
    "rowId": "125",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -1",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 1, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -1"
  },
  {
    "rowId": "126",
    "chartGroup": "Web Orders",
    "variableName": "Web_Order_count",
    "DataPoint": "Web Orders - Web_Order_count - Month -0",
    "serverName": "P21",
    "tableName": "p21_sales_history_report_view",
    "productionSqlExpression": "SELECT COUNT(DISTINCT order_no) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) + 1, 0);",
    "calculationType": "COUNT",
    "chartName": "Web Orders",
    "axisStep": "Month -0"
  },
  {
    "rowId": "127",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -11",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 11, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 10, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -11"
  },
  {
    "rowId": "128",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -10",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 10, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 9, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -10"
  },
  {
    "rowId": "129",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -9",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 9, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 8, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -9"
  },
  {
    "rowId": "130",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -8",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 8, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 7, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -8"
  },
  {
    "rowId": "131",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -7",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 7, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 6, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -7"
  },
  {
    "rowId": "132",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -6",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 6, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 5, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -6"
  },
  {
    "rowId": "133",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -5",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 5, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 4, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -5"
  },
  {
    "rowId": "134",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -4",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 4, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 3, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -4"
  },
  {
    "rowId": "135",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -3",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 3, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 2, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -3"
  },
  {
    "rowId": "136",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -2",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 2, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 1, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -2"
  },
  {
    "rowId": "137",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Month -1",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 1, 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -1"
  },
  {
    "rowId": "138",
    "chartGroup": "Web Revenue",
    "variableName": "Web_Order_value",
    "DataPoint": "Web Revenue - Web_Order_value - Current",
    "serverName": "P21",
    "tableName": "dbo.Orders",
    "productionSqlExpression": "SELECT ISNULL(SUM(total_sales), 0) AS value FROM p21_sales_history_report_view WITH (NOLOCK) WHERE (taker = 'INTERNET' OR job_name LIKE '%Web%' OR taker LIKE '%WEB%') AND invoice_date >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) AND invoice_date < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) + 1, 0);",
    "calculationType": "SUM",
    "chartName": "Web Revenue",
    "axisStep": "Month -0"
  },
  // POR Overview – simple table counts confirmed via introspection
  // RowIds continue sequentially after the previous entries (139-174 used above)
  {
    rowId: '175',
    chartGroup: 'POR Overview',
    variableName: 'PurchaseOrder_count',
    DataPoint: 'POR Overview - PurchaseOrder_count - Current',
    serverName: 'POR',
    tableName: 'PurchaseOrder',
    productionSqlExpression: 'SELECT Count(*) AS value FROM [PurchaseOrder];',
    calculationType: 'SUM',
    chartName: 'POR Overview',
    axisStep: 'Current',
  },
  {
    rowId: '176',
    chartGroup: 'POR Overview',
    variableName: 'PurchaseOrderDetail_count',
    DataPoint: 'POR Overview - PurchaseOrderDetail_count - Current',
    serverName: 'POR',
    tableName: 'PurchaseOrderDetail',
    productionSqlExpression: 'SELECT Count(*) AS value FROM [PurchaseOrderDetail];',
    calculationType: 'SUM',
    chartName: 'POR Overview',
    axisStep: 'Current',
  },
  {
    rowId: '177',
    chartGroup: 'POR Overview',
    variableName: 'CustomerFile_count',
    DataPoint: 'POR Overview - CustomerFile_count - Current',
    serverName: 'POR',
    tableName: 'CustomerFile',
    productionSqlExpression: 'SELECT Count(*) AS value FROM [CustomerFile];',
    calculationType: 'SUM',
    chartName: 'POR Overview',
    axisStep: 'Current',
  },
  {
    rowId: '178',
    chartGroup: 'POR Overview',
    variableName: 'MapGPSWorkOrders_count',
    DataPoint: 'POR Overview - MapGPSWorkOrders_count - Current',
    serverName: 'POR',
    tableName: 'MapGPSWorkOrders',
    productionSqlExpression: 'SELECT Count(*) AS value FROM [MapGPSWorkOrders];',
    calculationType: 'SUM',
    chartName: 'POR Overview',
    axisStep: 'Current',
  },
];

export const chartGroupSettings: any[] = [];
export const serverConfigs: any[] = [];
