import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// Import server initialization module
import '@/lib/db/server-init';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

if (typeof window !== 'undefined') {
  const originalError = console.error;
  console.error = (...args) => {
    if (args[0]?.includes?.('DOMNodeInserted') || args[0]?.includes?.('DOMNodeRemoved')) {
      return;
    }
    originalError.apply(console, args);
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
