# PowerShell script to rebuild the complete-chart-data.ts file
# This script will extract the original P21 entries and add the POR entries with correct SQL syntax

$filePath = "C:\Users\BobM\CascadeProjects\TallmanDashboard_new\lib\db\complete-chart-data.ts"
$backupPath = "C:\Users\BobM\CascadeProjects\TallmanDashboard_new\lib\db\complete-chart-data.ts.backup-full"
$tempFilePath = "C:\Users\BobM\CascadeProjects\TallmanDashboard_new\lib\db\complete-chart-data.temp.ts"
$newFilePath = "C:\Users\BobM\CascadeProjects\TallmanDashboard_new\lib\db\complete-chart-data.new.ts"

# Create a backup of the original file
Copy-Item -Path $filePath -Destination $backupPath -Force
Write-Host "Created backup at $backupPath"

# Define the file header
$fileHeader = @"
import type { SpreadsheetRow } from './types';

// This file was auto-generated by the generate-complete-chart-data.js script
// Last updated: $(Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffZ")

export const initialSpreadsheetData: SpreadsheetRow[] = [
"@

# Define the file footer
$fileFooter = @"
];

// Export the combined data
export const combinedData = initialSpreadsheetData;
"@

# Define the POR Overview entries with correct SQL syntax
$timestamp = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss.fffZ")

$porEntries = @"
  {
    "id": "127",
    "DataPoint": "POR Overview New Rentals, Jan",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 1 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "128",
    "DataPoint": "POR Overview New Rentals, Feb",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 2 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "129",
    "DataPoint": "POR Overview New Rentals, Mar",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 3 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "130",
    "DataPoint": "POR Overview New Rentals, Apr",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 4 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "131",
    "DataPoint": "POR Overview New Rentals, May",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 5 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "132",
    "DataPoint": "POR Overview New Rentals, Jun",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 6 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "133",
    "DataPoint": "POR Overview New Rentals, Jul",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 7 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "134",
    "DataPoint": "POR Overview New Rentals, Aug",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 8 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "135",
    "DataPoint": "POR Overview New Rentals, Sep",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 9 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "136",
    "DataPoint": "POR Overview New Rentals, Oct",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 10 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "137",
    "DataPoint": "POR Overview New Rentals, Nov",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 11 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "138",
    "DataPoint": "POR Overview New Rentals, Dec",
    "chartGroup": "POR Overview",
    "variableName": "New Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE Month(DateCreated) = 12 AND Year(DateCreated) = Year(Date())",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "139",
    "DataPoint": "POR Overview Open Rentals",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out')",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "140",
    "DataPoint": "POR Overview Open Rentals, Jan",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 1",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "141",
    "DataPoint": "POR Overview Open Rentals, Feb",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 2",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "142",
    "DataPoint": "POR Overview Open Rentals, Mar",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 3",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "143",
    "DataPoint": "POR Overview Open Rentals, Apr",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 4",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "144",
    "DataPoint": "POR Overview Open Rentals, May",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 5",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "145",
    "DataPoint": "POR Overview Open Rentals, Jun",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 6",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "146",
    "DataPoint": "POR Overview Open Rentals, Jul",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 7",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "147",
    "DataPoint": "POR Overview Open Rentals, Aug",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 8",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "148",
    "DataPoint": "POR Overview Open Rentals, Sep",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 9",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "149",
    "DataPoint": "POR Overview Open Rentals, Oct",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 10",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "150",
    "DataPoint": "POR Overview Open Rentals, Nov",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 11",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "151",
    "DataPoint": "POR Overview Open Rentals, Dec",
    "chartGroup": "POR Overview",
    "variableName": "Open Rentals",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Count(*) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 12",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "152",
    "DataPoint": "POR Overview Rental Value",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out')",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "153",
    "DataPoint": "POR Overview Rental Value, Jan",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 1",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "154",
    "DataPoint": "POR Overview Rental Value, Feb",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 2",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "155",
    "DataPoint": "POR Overview Rental Value, Mar",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 3",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "156",
    "DataPoint": "POR Overview Rental Value, Apr",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 4",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "157",
    "DataPoint": "POR Overview Rental Value, May",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 5",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "158",
    "DataPoint": "POR Overview Rental Value, Jun",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 6",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "159",
    "DataPoint": "POR Overview Rental Value, Jul",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 7",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "160",
    "DataPoint": "POR Overview Rental Value, Aug",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 8",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "161",
    "DataPoint": "POR Overview Rental Value, Sep",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 9",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "162",
    "DataPoint": "POR Overview Rental Value, Oct",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 10",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "163",
    "DataPoint": "POR Overview Rental Value, Nov",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 11",
    "lastUpdated": "$timestamp"
  },
  
  {
    "id": "164",
    "DataPoint": "POR Overview Rental Value, Dec",
    "chartGroup": "POR Overview",
    "variableName": "Rental Value",
    "serverName": "POR",
    "value": "0",
    "tableName": "Transactions",
    "calculation": "number",
    "productionSqlExpression": "SELECT Sum(TotalAmount) as value FROM Transactions WHERE TransactionStatus IN ('Open', 'Active', 'Out') AND Month(DateCreated) = 12",
    "lastUpdated": "$timestamp"
  }
"@

# Extract the P21 entries (IDs 1-126) from the backup file
try {
    # First, check if the backup file exists
    if (Test-Path $backupPath) {
        Write-Host "Reading P21 entries from backup file..."
        
        # Read the backup file
        $backupContent = Get-Content -Path $backupPath -Raw
        
        # Extract all JSON objects with IDs 1-126
        $p21Entries = @()
        
        for ($i = 1; $i -le 126; $i++) {
            $idPattern = [regex]::Escape("`"id`": `"$i`"")
            if ($backupContent -match $idPattern) {
                $startPos = $backupContent.IndexOf("{", $backupContent.IndexOf($idPattern))
                if ($startPos -ge 0) {
                    $depth = 1
                    $endPos = $startPos + 1
                    
                    while ($depth -gt 0 -and $endPos -lt $backupContent.Length) {
                        $char = $backupContent[$endPos]
                        if ($char -eq '{') {
                            $depth++
                        } elseif ($char -eq '}') {
                            $depth--
                        }
                        $endPos++
                    }
                    
                    if ($depth -eq 0) {
                        $entry = $backupContent.Substring($startPos, $endPos - $startPos)
                        $p21Entries += $entry
                    }
                }
            }
        }
        
        Write-Host "Found $($p21Entries.Count) P21 entries"
        
        # Create the new file with the P21 entries and POR entries
        $newContent = $fileHeader + "`r`n"
        
        # Add P21 entries
        foreach ($entry in $p21Entries) {
            $newContent += "  " + $entry + ",`r`n`r`n"
        }
        
        # Add POR entries
        $newContent += $porEntries + "`r`n"
        
        # Add file footer
        $newContent += $fileFooter
        
        # Write the new content to the new file
        Set-Content -Path $newFilePath -Value $newContent
        
        # Replace the original file with the new file
        Copy-Item -Path $newFilePath -Destination $filePath -Force
        
        # Clean up temporary files
        if (Test-Path $newFilePath) {
            Remove-Item -Path $newFilePath -Force
        }
        
        Write-Host "Successfully rebuilt complete-chart-data.ts with P21 and POR entries"
    } else {
        Write-Host "Backup file not found. Cannot extract P21 entries."
    }
} catch {
    Write-Host "Error: $_"
}

Write-Host "Complete-chart-data.ts has been rebuilt with proper P21 and POR entries!"
